DROP TABLE IF EXISTS "user_promocode" CASCADE;
DROP TABLE IF EXISTS "promocode_usage" CASCADE;
DROP TABLE IF EXISTS "promocode" CASCADE;
DROP TABLE IF EXISTS "idempotency_records" CASCADE;
DROP TABLE IF EXISTS "order_split" CASCADE;
DROP TABLE IF EXISTS "order_dish" CASCADE;
DROP TABLE IF EXISTS "order_review" CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;

DROP TYPE IF EXISTS split_status CASCADE;
DROP TYPE IF EXISTS order_status CASCADE;
