logger:
  level: "debug"

http:
  port: "8080"
  timeout: "10s"
  allowed_origins:
    - "http://localhost:3000"

grpc_clients:
  auth_service_addr: "localhost:50054"
  user_service_addr: "localhost:50052"
