logger:
  level: "debug"

http:
  port: "8080"
  timeout: "10s"
  allowed_origins:
    - "http://localhost:2033"

otel:
  service_name: "api-gateway"
  collector_addr: "otel-collector:4317"

grpc_clients:
  auth_service_addr: "localhost:50054"
  user_service_addr: "localhost:50052"
  restaurant_service_addr: "localhost:50053"
  cart_service_addr: "localhost:50055"
  address_service_addr: "localhost:50051"
  payment_service_addr: "localhost:50056"
  order_service_addr: "localhost:50057"
  analytics_service_addr: "localhost:50059"