CREATE DATABASE auth_db;
CREATE DATABASE user_db;
CREATE DATABASE restaurant_db;
CREATE DATABASE cart_db;
CREATE DATABASE address_db;
CREATE DATABASE payment_db;
CREATE DATABASE order_db;
CREATE DATABASE support_db;
