// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/usecase (interfaces: DishUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/dish_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/usecase DishUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDishUseCase is a mock of DishUseCase interface.
type MockDishUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDishUseCaseMockRecorder
	isgomock struct{}
}

// MockDishUseCaseMockRecorder is the mock recorder for MockDishUseCase.
type MockDishUseCaseMockRecorder struct {
	mock *MockDishUseCase
}

// NewMockDishUseCase creates a new mock instance.
func NewMockDishUseCase(ctrl *gomock.Controller) *MockDishUseCase {
	mock := &MockDishUseCase{ctrl: ctrl}
	mock.recorder = &MockDishUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDishUseCase) EXPECT() *MockDishUseCaseMockRecorder {
	return m.recorder
}

// CreateDish mocks base method.
func (m *MockDishUseCase) CreateDish(ctx context.Context, d domain.Dish, image []byte, idemKey string) (domain.Dish, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDish", ctx, d, image, idemKey)
	ret0, _ := ret[0].(domain.Dish)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDish indicates an expected call of CreateDish.
func (mr *MockDishUseCaseMockRecorder) CreateDish(ctx, d, image, idemKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDish", reflect.TypeOf((*MockDishUseCase)(nil).CreateDish), ctx, d, image, idemKey)
}

// DeleteDish mocks base method.
func (m *MockDishUseCase) DeleteDish(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDish", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDish indicates an expected call of DeleteDish.
func (mr *MockDishUseCaseMockRecorder) DeleteDish(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDish", reflect.TypeOf((*MockDishUseCase)(nil).DeleteDish), ctx, id)
}

// GetDishesByIDs mocks base method.
func (m *MockDishUseCase) GetDishesByIDs(ctx context.Context, ids []int64) ([]domain.Dish, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDishesByIDs", ctx, ids)
	ret0, _ := ret[0].([]domain.Dish)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDishesByIDs indicates an expected call of GetDishesByIDs.
func (mr *MockDishUseCaseMockRecorder) GetDishesByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDishesByIDs", reflect.TypeOf((*MockDishUseCase)(nil).GetDishesByIDs), ctx, ids)
}

// GetDishesByRestaurantBrandID mocks base method.
func (m *MockDishUseCase) GetDishesByRestaurantBrandID(ctx context.Context, restaurantBrandID int64, limit, offset int) ([]domain.Dish, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDishesByRestaurantBrandID", ctx, restaurantBrandID, limit, offset)
	ret0, _ := ret[0].([]domain.Dish)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDishesByRestaurantBrandID indicates an expected call of GetDishesByRestaurantBrandID.
func (mr *MockDishUseCaseMockRecorder) GetDishesByRestaurantBrandID(ctx, restaurantBrandID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDishesByRestaurantBrandID", reflect.TypeOf((*MockDishUseCase)(nil).GetDishesByRestaurantBrandID), ctx, restaurantBrandID, limit, offset)
}

// SearchDishes mocks base method.
func (m *MockDishUseCase) SearchDishes(ctx context.Context, query string, limit int) ([]domain.Dish, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchDishes", ctx, query, limit)
	ret0, _ := ret[0].([]domain.Dish)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDishes indicates an expected call of SearchDishes.
func (mr *MockDishUseCaseMockRecorder) SearchDishes(ctx, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDishes", reflect.TypeOf((*MockDishUseCase)(nil).SearchDishes), ctx, query, limit)
}

// SearchDishesByBrand mocks base method.
func (m *MockDishUseCase) SearchDishesByBrand(ctx context.Context, brandID int64, query string, limit int) ([]domain.Dish, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchDishesByBrand", ctx, brandID, query, limit)
	ret0, _ := ret[0].([]domain.Dish)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDishesByBrand indicates an expected call of SearchDishesByBrand.
func (mr *MockDishUseCaseMockRecorder) SearchDishesByBrand(ctx, brandID, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDishesByBrand", reflect.TypeOf((*MockDishUseCase)(nil).SearchDishesByBrand), ctx, brandID, query, limit)
}

// UpdateDish mocks base method.
func (m *MockDishUseCase) UpdateDish(ctx context.Context, d domain.Dish, newImage []byte, idemKey string) (domain.Dish, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDish", ctx, d, newImage, idemKey)
	ret0, _ := ret[0].(domain.Dish)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDish indicates an expected call of UpdateDish.
func (mr *MockDishUseCaseMockRecorder) UpdateDish(ctx, d, newImage, idemKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDish", reflect.TypeOf((*MockDishUseCase)(nil).UpdateDish), ctx, d, newImage, idemKey)
}
