// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/usecase (interfaces: RecommendationsUseCase,OrderHistoryClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/recommendations_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/usecase RecommendationsUseCase,OrderHistoryClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRecommendationsUseCase is a mock of RecommendationsUseCase interface.
type MockRecommendationsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRecommendationsUseCaseMockRecorder
	isgomock struct{}
}

// MockRecommendationsUseCaseMockRecorder is the mock recorder for MockRecommendationsUseCase.
type MockRecommendationsUseCaseMockRecorder struct {
	mock *MockRecommendationsUseCase
}

// NewMockRecommendationsUseCase creates a new mock instance.
func NewMockRecommendationsUseCase(ctrl *gomock.Controller) *MockRecommendationsUseCase {
	mock := &MockRecommendationsUseCase{ctrl: ctrl}
	mock.recorder = &MockRecommendationsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecommendationsUseCase) EXPECT() *MockRecommendationsUseCaseMockRecorder {
	return m.recorder
}

// GetRecommendations mocks base method.
func (m *MockRecommendationsUseCase) GetRecommendations(ctx context.Context, userID int64, limit int) ([]domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecommendations", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecommendations indicates an expected call of GetRecommendations.
func (mr *MockRecommendationsUseCaseMockRecorder) GetRecommendations(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecommendations", reflect.TypeOf((*MockRecommendationsUseCase)(nil).GetRecommendations), ctx, userID, limit)
}

// MockOrderHistoryClient is a mock of OrderHistoryClient interface.
type MockOrderHistoryClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrderHistoryClientMockRecorder
	isgomock struct{}
}

// MockOrderHistoryClientMockRecorder is the mock recorder for MockOrderHistoryClient.
type MockOrderHistoryClientMockRecorder struct {
	mock *MockOrderHistoryClient
}

// NewMockOrderHistoryClient creates a new mock instance.
func NewMockOrderHistoryClient(ctrl *gomock.Controller) *MockOrderHistoryClient {
	mock := &MockOrderHistoryClient{ctrl: ctrl}
	mock.recorder = &MockOrderHistoryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderHistoryClient) EXPECT() *MockOrderHistoryClientMockRecorder {
	return m.recorder
}

// GetTrendingBrands mocks base method.
func (m *MockOrderHistoryClient) GetTrendingBrands(ctx context.Context, windowDays, limit int32) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrendingBrands", ctx, windowDays, limit)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrendingBrands indicates an expected call of GetTrendingBrands.
func (mr *MockOrderHistoryClientMockRecorder) GetTrendingBrands(ctx, windowDays, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrendingBrands", reflect.TypeOf((*MockOrderHistoryClient)(nil).GetTrendingBrands), ctx, windowDays, limit)
}

// GetUserPaidBrands mocks base method.
func (m *MockOrderHistoryClient) GetUserPaidBrands(ctx context.Context, userID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPaidBrands", ctx, userID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPaidBrands indicates an expected call of GetUserPaidBrands.
func (mr *MockOrderHistoryClientMockRecorder) GetUserPaidBrands(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPaidBrands", reflect.TypeOf((*MockOrderHistoryClient)(nil).GetUserPaidBrands), ctx, userID)
}
