// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/usecase (interfaces: RestaurantBrandUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/restaurant_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/usecase RestaurantBrandUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRestaurantBrandUseCase is a mock of RestaurantBrandUseCase interface.
type MockRestaurantBrandUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRestaurantBrandUseCaseMockRecorder
	isgomock struct{}
}

// MockRestaurantBrandUseCaseMockRecorder is the mock recorder for MockRestaurantBrandUseCase.
type MockRestaurantBrandUseCaseMockRecorder struct {
	mock *MockRestaurantBrandUseCase
}

// NewMockRestaurantBrandUseCase creates a new mock instance.
func NewMockRestaurantBrandUseCase(ctrl *gomock.Controller) *MockRestaurantBrandUseCase {
	mock := &MockRestaurantBrandUseCase{ctrl: ctrl}
	mock.recorder = &MockRestaurantBrandUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestaurantBrandUseCase) EXPECT() *MockRestaurantBrandUseCaseMockRecorder {
	return m.recorder
}

// CreateRestaurantBrand mocks base method.
func (m *MockRestaurantBrandUseCase) CreateRestaurantBrand(ctx context.Context, b domain.RestaurantBrand, image []byte, idemKey string) (domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRestaurantBrand", ctx, b, image, idemKey)
	ret0, _ := ret[0].(domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRestaurantBrand indicates an expected call of CreateRestaurantBrand.
func (mr *MockRestaurantBrandUseCaseMockRecorder) CreateRestaurantBrand(ctx, b, image, idemKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRestaurantBrand", reflect.TypeOf((*MockRestaurantBrandUseCase)(nil).CreateRestaurantBrand), ctx, b, image, idemKey)
}

// DeleteRestaurantBrand mocks base method.
func (m *MockRestaurantBrandUseCase) DeleteRestaurantBrand(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRestaurantBrand", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRestaurantBrand indicates an expected call of DeleteRestaurantBrand.
func (mr *MockRestaurantBrandUseCaseMockRecorder) DeleteRestaurantBrand(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRestaurantBrand", reflect.TypeOf((*MockRestaurantBrandUseCase)(nil).DeleteRestaurantBrand), ctx, id)
}

// GetRestaurantBrandByID mocks base method.
func (m *MockRestaurantBrandUseCase) GetRestaurantBrandByID(ctx context.Context, id int64) (domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurantBrandByID", ctx, id)
	ret0, _ := ret[0].(domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestaurantBrandByID indicates an expected call of GetRestaurantBrandByID.
func (mr *MockRestaurantBrandUseCaseMockRecorder) GetRestaurantBrandByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurantBrandByID", reflect.TypeOf((*MockRestaurantBrandUseCase)(nil).GetRestaurantBrandByID), ctx, id)
}

// GetRestaurantBrandsByCategoryName mocks base method.
func (m *MockRestaurantBrandUseCase) GetRestaurantBrandsByCategoryName(ctx context.Context, categoryName string, limit, offset int) ([]domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurantBrandsByCategoryName", ctx, categoryName, limit, offset)
	ret0, _ := ret[0].([]domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestaurantBrandsByCategoryName indicates an expected call of GetRestaurantBrandsByCategoryName.
func (mr *MockRestaurantBrandUseCaseMockRecorder) GetRestaurantBrandsByCategoryName(ctx, categoryName, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurantBrandsByCategoryName", reflect.TypeOf((*MockRestaurantBrandUseCase)(nil).GetRestaurantBrandsByCategoryName), ctx, categoryName, limit, offset)
}

// GetRestaurantBrandsByIDs mocks base method.
func (m *MockRestaurantBrandUseCase) GetRestaurantBrandsByIDs(ctx context.Context, brandIDs []int64) ([]domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurantBrandsByIDs", ctx, brandIDs)
	ret0, _ := ret[0].([]domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestaurantBrandsByIDs indicates an expected call of GetRestaurantBrandsByIDs.
func (mr *MockRestaurantBrandUseCaseMockRecorder) GetRestaurantBrandsByIDs(ctx, brandIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurantBrandsByIDs", reflect.TypeOf((*MockRestaurantBrandUseCase)(nil).GetRestaurantBrandsByIDs), ctx, brandIDs)
}

// GetRestaurantBrandsList mocks base method.
func (m *MockRestaurantBrandUseCase) GetRestaurantBrandsList(ctx context.Context, limit, offset int) ([]domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurantBrandsList", ctx, limit, offset)
	ret0, _ := ret[0].([]domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestaurantBrandsList indicates an expected call of GetRestaurantBrandsList.
func (mr *MockRestaurantBrandUseCaseMockRecorder) GetRestaurantBrandsList(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurantBrandsList", reflect.TypeOf((*MockRestaurantBrandUseCase)(nil).GetRestaurantBrandsList), ctx, limit, offset)
}

// SearchRestaurantBrands mocks base method.
func (m *MockRestaurantBrandUseCase) SearchRestaurantBrands(ctx context.Context, query string, limit, offset int) ([]domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRestaurantBrands", ctx, query, limit, offset)
	ret0, _ := ret[0].([]domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRestaurantBrands indicates an expected call of SearchRestaurantBrands.
func (mr *MockRestaurantBrandUseCaseMockRecorder) SearchRestaurantBrands(ctx, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRestaurantBrands", reflect.TypeOf((*MockRestaurantBrandUseCase)(nil).SearchRestaurantBrands), ctx, query, limit, offset)
}

// UpdateRestaurantBrand mocks base method.
func (m *MockRestaurantBrandUseCase) UpdateRestaurantBrand(ctx context.Context, b domain.RestaurantBrand, newImage []byte, idemKey string) (domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRestaurantBrand", ctx, b, newImage, idemKey)
	ret0, _ := ret[0].(domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRestaurantBrand indicates an expected call of UpdateRestaurantBrand.
func (mr *MockRestaurantBrandUseCaseMockRecorder) UpdateRestaurantBrand(ctx, b, newImage, idemKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRestaurantBrand", reflect.TypeOf((*MockRestaurantBrandUseCase)(nil).UpdateRestaurantBrand), ctx, b, newImage, idemKey)
}
