apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        send_batch_size: 50
        timeout: 10s

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: "nancats"

      otlp/jaeger:
        endpoint: "jaeger:4317" # Шлем трейсы в сервис jaeger
        tls:
          insecure: true

      debug:
        verbosity: basic

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, debug]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: default
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8889"
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        args: ["--config=/etc/otel-collector/otel-collector.yaml"]
        resources:
          limits:
            memory: "150Mi"
          requests:
            memory: "50Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/otel-collector
        ports:
        - containerPort: 4317 # OTLP gRPC
        - containerPort: 8889 # Метрики Prometheus
      volumes:
      - name: config-volume
        configMap:
          name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: default
spec:
  selector:
    app: otel-collector
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: prometheus
    port: 8889
    targetPort: 8889