// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_NaNcats/services/user/internal/usecase (interfaces: AchievementUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/achievement_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_NaNcats/services/user/internal/usecase AchievementUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/go-park-mail-ru/2026_1_NaNcats/services/user/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAchievementUseCase is a mock of AchievementUseCase interface.
type MockAchievementUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAchievementUseCaseMockRecorder
	isgomock struct{}
}

// MockAchievementUseCaseMockRecorder is the mock recorder for MockAchievementUseCase.
type MockAchievementUseCaseMockRecorder struct {
	mock *MockAchievementUseCase
}

// NewMockAchievementUseCase creates a new mock instance.
func NewMockAchievementUseCase(ctrl *gomock.Controller) *MockAchievementUseCase {
	mock := &MockAchievementUseCase{ctrl: ctrl}
	mock.recorder = &MockAchievementUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAchievementUseCase) EXPECT() *MockAchievementUseCaseMockRecorder {
	return m.recorder
}

// ListAll mocks base method.
func (m *MockAchievementUseCase) ListAll(ctx context.Context) ([]domain.Achievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]domain.Achievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockAchievementUseCaseMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockAchievementUseCase)(nil).ListAll), ctx)
}

// ListForUser mocks base method.
func (m *MockAchievementUseCase) ListForUser(ctx context.Context, accountID int64) ([]domain.UserAchievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForUser", ctx, accountID)
	ret0, _ := ret[0].([]domain.UserAchievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForUser indicates an expected call of ListForUser.
func (mr *MockAchievementUseCaseMockRecorder) ListForUser(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForUser", reflect.TypeOf((*MockAchievementUseCase)(nil).ListForUser), ctx, accountID)
}

// OnOrderPaid mocks base method.
func (m *MockAchievementUseCase) OnOrderPaid(ctx context.Context, accountID, restaurantID int64, paidAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnOrderPaid", ctx, accountID, restaurantID, paidAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnOrderPaid indicates an expected call of OnOrderPaid.
func (mr *MockAchievementUseCaseMockRecorder) OnOrderPaid(ctx, accountID, restaurantID, paidAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnOrderPaid", reflect.TypeOf((*MockAchievementUseCase)(nil).OnOrderPaid), ctx, accountID, restaurantID, paidAt)
}

// OnWheelSpin mocks base method.
func (m *MockAchievementUseCase) OnWheelSpin(ctx context.Context, accountID int64, wonCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnWheelSpin", ctx, accountID, wonCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnWheelSpin indicates an expected call of OnWheelSpin.
func (mr *MockAchievementUseCaseMockRecorder) OnWheelSpin(ctx, accountID, wonCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnWheelSpin", reflect.TypeOf((*MockAchievementUseCase)(nil).OnWheelSpin), ctx, accountID, wonCode)
}

// OnWordleResult mocks base method.
func (m *MockAchievementUseCase) OnWordleResult(ctx context.Context, accountID int64, isWin bool, totalWins, currentStreak int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnWordleResult", ctx, accountID, isWin, totalWins, currentStreak)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnWordleResult indicates an expected call of OnWordleResult.
func (mr *MockAchievementUseCaseMockRecorder) OnWordleResult(ctx, accountID, isWin, totalWins, currentStreak any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnWordleResult", reflect.TypeOf((*MockAchievementUseCase)(nil).OnWordleResult), ctx, accountID, isWin, totalWins, currentStreak)
}
