// Code generated by MockGen. DO NOT EDIT.
// Source: client_profile.go
//
// Generated by this command:
//
//	mockgen -source=client_profile.go -destination=mocks/client_profile_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_NaNcats/services/user/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockClientProfileUseCase is a mock of ClientProfileUseCase interface.
type MockClientProfileUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockClientProfileUseCaseMockRecorder
	isgomock struct{}
}

// MockClientProfileUseCaseMockRecorder is the mock recorder for MockClientProfileUseCase.
type MockClientProfileUseCaseMockRecorder struct {
	mock *MockClientProfileUseCase
}

// NewMockClientProfileUseCase creates a new mock instance.
func NewMockClientProfileUseCase(ctrl *gomock.Controller) *MockClientProfileUseCase {
	mock := &MockClientProfileUseCase{ctrl: ctrl}
	mock.recorder = &MockClientProfileUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientProfileUseCase) EXPECT() *MockClientProfileUseCaseMockRecorder {
	return m.recorder
}

// ActivateStreakFreeze mocks base method.
func (m *MockClientProfileUseCase) ActivateStreakFreeze(ctx context.Context, accountID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateStreakFreeze", ctx, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateStreakFreeze indicates an expected call of ActivateStreakFreeze.
func (mr *MockClientProfileUseCaseMockRecorder) ActivateStreakFreeze(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateStreakFreeze", reflect.TypeOf((*MockClientProfileUseCase)(nil).ActivateStreakFreeze), ctx, accountID)
}

// ClaimWheelSpin mocks base method.
func (m *MockClientProfileUseCase) ClaimWheelSpin(ctx context.Context, accountID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimWheelSpin", ctx, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClaimWheelSpin indicates an expected call of ClaimWheelSpin.
func (mr *MockClientProfileUseCaseMockRecorder) ClaimWheelSpin(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimWheelSpin", reflect.TypeOf((*MockClientProfileUseCase)(nil).ClaimWheelSpin), ctx, accountID)
}

// CreateProfile mocks base method.
func (m *MockClientProfileUseCase) CreateProfile(ctx context.Context, accountID int64, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", ctx, accountID, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockClientProfileUseCaseMockRecorder) CreateProfile(ctx, accountID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockClientProfileUseCase)(nil).CreateProfile), ctx, accountID, idempotencyKey)
}

// GetByAccountID mocks base method.
func (m *MockClientProfileUseCase) GetByAccountID(ctx context.Context, accountID int64) (domain.ClientProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountID", ctx, accountID)
	ret0, _ := ret[0].(domain.ClientProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccountID indicates an expected call of GetByAccountID.
func (mr *MockClientProfileUseCaseMockRecorder) GetByAccountID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountID", reflect.TypeOf((*MockClientProfileUseCase)(nil).GetByAccountID), ctx, accountID)
}

// GetWheelSectors mocks base method.
func (m *MockClientProfileUseCase) GetWheelSectors(ctx context.Context) ([]domain.WheelSector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWheelSectors", ctx)
	ret0, _ := ret[0].([]domain.WheelSector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWheelSectors indicates an expected call of GetWheelSectors.
func (mr *MockClientProfileUseCaseMockRecorder) GetWheelSectors(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWheelSectors", reflect.TypeOf((*MockClientProfileUseCase)(nil).GetWheelSectors), ctx)
}

// IncrementStreak mocks base method.
func (m *MockClientProfileUseCase) IncrementStreak(ctx context.Context, accountID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementStreak", ctx, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementStreak indicates an expected call of IncrementStreak.
func (mr *MockClientProfileUseCaseMockRecorder) IncrementStreak(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementStreak", reflect.TypeOf((*MockClientProfileUseCase)(nil).IncrementStreak), ctx, accountID)
}

// ResetWheelSpinCooldown mocks base method.
func (m *MockClientProfileUseCase) ResetWheelSpinCooldown(ctx context.Context, accountID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetWheelSpinCooldown", ctx, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetWheelSpinCooldown indicates an expected call of ResetWheelSpinCooldown.
func (mr *MockClientProfileUseCaseMockRecorder) ResetWheelSpinCooldown(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetWheelSpinCooldown", reflect.TypeOf((*MockClientProfileUseCase)(nil).ResetWheelSpinCooldown), ctx, accountID)
}

// SpinWheel mocks base method.
func (m *MockClientProfileUseCase) SpinWheel(ctx context.Context, userID int64) (domain.WheelSpinResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpinWheel", ctx, userID)
	ret0, _ := ret[0].(domain.WheelSpinResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpinWheel indicates an expected call of SpinWheel.
func (mr *MockClientProfileUseCaseMockRecorder) SpinWheel(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpinWheel", reflect.TypeOf((*MockClientProfileUseCase)(nil).SpinWheel), ctx, userID)
}

// MockOrderClient is a mock of OrderClient interface.
type MockOrderClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrderClientMockRecorder
	isgomock struct{}
}

// MockOrderClientMockRecorder is the mock recorder for MockOrderClient.
type MockOrderClientMockRecorder struct {
	mock *MockOrderClient
}

// NewMockOrderClient creates a new mock instance.
func NewMockOrderClient(ctrl *gomock.Controller) *MockOrderClient {
	mock := &MockOrderClient{ctrl: ctrl}
	mock.recorder = &MockOrderClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderClient) EXPECT() *MockOrderClientMockRecorder {
	return m.recorder
}

// CreateAndBindWheelPromo mocks base method.
func (m *MockOrderClient) CreateAndBindWheelPromo(ctx context.Context, userID int64, title string, discountAmount *int64, discountPercent *int, brandID, minOrderAmount *int64) (string, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAndBindWheelPromo", ctx, userID, title, discountAmount, discountPercent, brandID, minOrderAmount)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateAndBindWheelPromo indicates an expected call of CreateAndBindWheelPromo.
func (mr *MockOrderClientMockRecorder) CreateAndBindWheelPromo(ctx, userID, title, discountAmount, discountPercent, brandID, minOrderAmount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAndBindWheelPromo", reflect.TypeOf((*MockOrderClient)(nil).CreateAndBindWheelPromo), ctx, userID, title, discountAmount, discountPercent, brandID, minOrderAmount)
}

// GetTrendingBrands mocks base method.
func (m *MockOrderClient) GetTrendingBrands(ctx context.Context, windowDays, limit int32) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrendingBrands", ctx, windowDays, limit)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrendingBrands indicates an expected call of GetTrendingBrands.
func (mr *MockOrderClientMockRecorder) GetTrendingBrands(ctx, windowDays, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrendingBrands", reflect.TypeOf((*MockOrderClient)(nil).GetTrendingBrands), ctx, windowDays, limit)
}
