version: '3.8'
services:
  db:
    image: postgis/postgis:18-3.6-alpine # Образ с Postgres + PostGIS
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      # сохраняет таблицы и данные пользователей
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # Проверка готовности базы
      # бэкенд не начнет пытаться подключиться к базе, пока она не будет готова принимать соединения
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    
  backend:
    build: .
    container_name: go_backend
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    environment:
      # Передаем URL базы данных Go-приложению
      DATABASE_URL: ${DATABASE_URL}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    depends_on:
      db:
        condition: service_healthy # Запускать бэкенд только когда база полностью готова
    restart: always

volumes:
  # Объявляем именованный том для базы
  postgres_data: