// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../shared/templates/tracing.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package usecase

//go:generate gowrap gen -p github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/usecase -i RestaurantBrandUseCase -t ../../../../shared/templates/tracing.tmpl -o restaurant_brand_tracing_mw.go -v TracerName=restaurant-service -l ""

import (
	"context"

	"github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/domain"
	"go.opentelemetry.io/otel"
	otelcodes "go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

// RestaurantBrandUseCaseTracingMiddleware реализует интерфейс RestaurantBrandUseCase с поддержкой трассировки OpenTelemetry
type RestaurantBrandUseCaseTracingMiddleware struct {
	next   RestaurantBrandUseCase
	tracer trace.Tracer
}

// NewRestaurantBrandUseCaseTracingMiddleware создает новый экземпляр декоратора для трассировки
func NewRestaurantBrandUseCaseTracingMiddleware(next RestaurantBrandUseCase) RestaurantBrandUseCaseTracingMiddleware {
	return RestaurantBrandUseCaseTracingMiddleware{
		next:   next,
		tracer: otel.Tracer("restaurant-service"),
	}
}

// CreateRestaurantBrand трассирует выполнение метода CreateRestaurantBrand
func (m RestaurantBrandUseCaseTracingMiddleware) CreateRestaurantBrand(ctx context.Context, b domain.RestaurantBrand, image []byte, idemKey string) (r1 domain.RestaurantBrand, err error) {

	ctx, span := m.tracer.Start(ctx, "RestaurantBrandUseCase.CreateRestaurantBrand")

	defer span.End()

	r1, err = m.next.CreateRestaurantBrand(ctx, b, image, idemKey)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// DeleteRestaurantBrand трассирует выполнение метода DeleteRestaurantBrand
func (m RestaurantBrandUseCaseTracingMiddleware) DeleteRestaurantBrand(ctx context.Context, id int64) (err error) {

	ctx, span := m.tracer.Start(ctx, "RestaurantBrandUseCase.DeleteRestaurantBrand")

	defer span.End()

	err = m.next.DeleteRestaurantBrand(ctx, id)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// GetRestaurantBrandByID трассирует выполнение метода GetRestaurantBrandByID
func (m RestaurantBrandUseCaseTracingMiddleware) GetRestaurantBrandByID(ctx context.Context, id int64) (r1 domain.RestaurantBrand, err error) {

	ctx, span := m.tracer.Start(ctx, "RestaurantBrandUseCase.GetRestaurantBrandByID")

	defer span.End()

	r1, err = m.next.GetRestaurantBrandByID(ctx, id)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// GetRestaurantBrandsByIDs трассирует выполнение метода GetRestaurantBrandsByIDs
func (m RestaurantBrandUseCaseTracingMiddleware) GetRestaurantBrandsByIDs(ctx context.Context, brandIDs []int64) (ra1 []domain.RestaurantBrand, err error) {

	ctx, span := m.tracer.Start(ctx, "RestaurantBrandUseCase.GetRestaurantBrandsByIDs")

	defer span.End()

	ra1, err = m.next.GetRestaurantBrandsByIDs(ctx, brandIDs)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// GetRestaurantBrandsList трассирует выполнение метода GetRestaurantBrandsList
func (m RestaurantBrandUseCaseTracingMiddleware) GetRestaurantBrandsList(ctx context.Context, limit int, offset int) (ra1 []domain.RestaurantBrand, err error) {

	ctx, span := m.tracer.Start(ctx, "RestaurantBrandUseCase.GetRestaurantBrandsList")

	defer span.End()

	ra1, err = m.next.GetRestaurantBrandsList(ctx, limit, offset)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// UpdateRestaurantBrand трассирует выполнение метода UpdateRestaurantBrand
func (m RestaurantBrandUseCaseTracingMiddleware) UpdateRestaurantBrand(ctx context.Context, b domain.RestaurantBrand, newImage []byte, idemKey string) (r1 domain.RestaurantBrand, err error) {

	ctx, span := m.tracer.Start(ctx, "RestaurantBrandUseCase.UpdateRestaurantBrand")

	defer span.End()

	r1, err = m.next.UpdateRestaurantBrand(ctx, b, newImage, idemKey)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}
