// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package events

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF9e6cb91DecodeGithubComGoParkMailRu20261NaNcatsSharedPkgRabbitmqEvents(in *jlexer.Lexer, out *UserRoleChangedEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "old_role":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OldRole = string(in.String())
			}
		case "new_role":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NewRole = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF9e6cb91EncodeGithubComGoParkMailRu20261NaNcatsSharedPkgRabbitmqEvents(out *jwriter.Writer, in UserRoleChangedEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"old_role\":"
		out.RawString(prefix)
		out.String(string(in.OldRole))
	}
	{
		const prefix string = ",\"new_role\":"
		out.RawString(prefix)
		out.String(string(in.NewRole))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserRoleChangedEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF9e6cb91EncodeGithubComGoParkMailRu20261NaNcatsSharedPkgRabbitmqEvents(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserRoleChangedEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF9e6cb91EncodeGithubComGoParkMailRu20261NaNcatsSharedPkgRabbitmqEvents(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserRoleChangedEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF9e6cb91DecodeGithubComGoParkMailRu20261NaNcatsSharedPkgRabbitmqEvents(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserRoleChangedEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF9e6cb91DecodeGithubComGoParkMailRu20261NaNcatsSharedPkgRabbitmqEvents(l, v)
}
