logger:
  level: "debug"

postgres:
  url: "postgres://user:pass@localhost:5435/cart_db?sslmode=disable"

grpc:
  port: "50055"
  timeout: "2s"

restaurant_service_addr: "localhost:50053"
default_food_logo_url: "https://nancats-bucket.storage.yandexcloud.net/foods/default-food-logo.webp"