// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_NaNcats/services/order/internal/repository (interfaces: PromoRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/promo_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_NaNcats/services/order/internal/repository PromoRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_NaNcats/services/order/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPromoRepository is a mock of PromoRepository interface.
type MockPromoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPromoRepositoryMockRecorder
	isgomock struct{}
}

// MockPromoRepositoryMockRecorder is the mock recorder for MockPromoRepository.
type MockPromoRepositoryMockRecorder struct {
	mock *MockPromoRepository
}

// NewMockPromoRepository creates a new mock instance.
func NewMockPromoRepository(ctrl *gomock.Controller) *MockPromoRepository {
	mock := &MockPromoRepository{ctrl: ctrl}
	mock.recorder = &MockPromoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromoRepository) EXPECT() *MockPromoRepositoryMockRecorder {
	return m.recorder
}

// BindPromocodeToUser mocks base method.
func (m *MockPromoRepository) BindPromocodeToUser(ctx context.Context, userID, promoID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindPromocodeToUser", ctx, userID, promoID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BindPromocodeToUser indicates an expected call of BindPromocodeToUser.
func (mr *MockPromoRepositoryMockRecorder) BindPromocodeToUser(ctx, userID, promoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindPromocodeToUser", reflect.TypeOf((*MockPromoRepository)(nil).BindPromocodeToUser), ctx, userID, promoID)
}

// CountUserPromocodeUsage mocks base method.
func (m *MockPromoRepository) CountUserPromocodeUsage(ctx context.Context, promoID, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserPromocodeUsage", ctx, promoID, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserPromocodeUsage indicates an expected call of CountUserPromocodeUsage.
func (mr *MockPromoRepositoryMockRecorder) CountUserPromocodeUsage(ctx, promoID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserPromocodeUsage", reflect.TypeOf((*MockPromoRepository)(nil).CountUserPromocodeUsage), ctx, promoID, userID)
}

// CreatePromocode mocks base method.
func (m *MockPromoRepository) CreatePromocode(ctx context.Context, promo domain.Promocode) (domain.Promocode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePromocode", ctx, promo)
	ret0, _ := ret[0].(domain.Promocode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePromocode indicates an expected call of CreatePromocode.
func (mr *MockPromoRepositoryMockRecorder) CreatePromocode(ctx, promo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePromocode", reflect.TypeOf((*MockPromoRepository)(nil).CreatePromocode), ctx, promo)
}

// GetPromocodeByCode mocks base method.
func (m *MockPromoRepository) GetPromocodeByCode(ctx context.Context, code string) (domain.Promocode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromocodeByCode", ctx, code)
	ret0, _ := ret[0].(domain.Promocode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromocodeByCode indicates an expected call of GetPromocodeByCode.
func (mr *MockPromoRepositoryMockRecorder) GetPromocodeByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromocodeByCode", reflect.TypeOf((*MockPromoRepository)(nil).GetPromocodeByCode), ctx, code)
}

// GetRestaurantPromocodes mocks base method.
func (m *MockPromoRepository) GetRestaurantPromocodes(ctx context.Context, brandID int64) ([]domain.Promocode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurantPromocodes", ctx, brandID)
	ret0, _ := ret[0].([]domain.Promocode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestaurantPromocodes indicates an expected call of GetRestaurantPromocodes.
func (mr *MockPromoRepositoryMockRecorder) GetRestaurantPromocodes(ctx, brandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurantPromocodes", reflect.TypeOf((*MockPromoRepository)(nil).GetRestaurantPromocodes), ctx, brandID)
}

// GetUserPromocodes mocks base method.
func (m *MockPromoRepository) GetUserPromocodes(ctx context.Context, userID int64) ([]domain.Promocode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPromocodes", ctx, userID)
	ret0, _ := ret[0].([]domain.Promocode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPromocodes indicates an expected call of GetUserPromocodes.
func (mr *MockPromoRepositoryMockRecorder) GetUserPromocodes(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPromocodes", reflect.TypeOf((*MockPromoRepository)(nil).GetUserPromocodes), ctx, userID)
}

// RecordPromocodeUsage mocks base method.
func (m *MockPromoRepository) RecordPromocodeUsage(ctx context.Context, promoID, userID int64, orderID *int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordPromocodeUsage", ctx, promoID, userID, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordPromocodeUsage indicates an expected call of RecordPromocodeUsage.
func (mr *MockPromoRepositoryMockRecorder) RecordPromocodeUsage(ctx, promoID, userID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPromocodeUsage", reflect.TypeOf((*MockPromoRepository)(nil).RecordPromocodeUsage), ctx, promoID, userID, orderID)
}

// ResolveOrderInternalID mocks base method.
func (m *MockPromoRepository) ResolveOrderInternalID(ctx context.Context, orderPublicID string) (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveOrderInternalID", ctx, orderPublicID)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveOrderInternalID indicates an expected call of ResolveOrderInternalID.
func (mr *MockPromoRepositoryMockRecorder) ResolveOrderInternalID(ctx, orderPublicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveOrderInternalID", reflect.TypeOf((*MockPromoRepository)(nil).ResolveOrderInternalID), ctx, orderPublicID)
}
