// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  handler

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( AddressRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AddressRequest ) UnmarshalJSON([]byte) error { return nil }
func ( AddressRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AddressRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AddressRequest *AddressRequest
