DROP TABLE IF EXISTS "owner_profile" CASCADE;
DROP TABLE IF EXISTS "courier_profile" CASCADE;
DROP TABLE IF EXISTS "client_profile" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

DROP TYPE IF EXISTS courier_status CASCADE;
