// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_NaNcats/internal/usecase (interfaces: AddressUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/address_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_NaNcats/internal/usecase AddressUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_NaNcats/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAddressUseCase is a mock of AddressUseCase interface.
type MockAddressUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAddressUseCaseMockRecorder
	isgomock struct{}
}

// MockAddressUseCaseMockRecorder is the mock recorder for MockAddressUseCase.
type MockAddressUseCaseMockRecorder struct {
	mock *MockAddressUseCase
}

// NewMockAddressUseCase creates a new mock instance.
func NewMockAddressUseCase(ctrl *gomock.Controller) *MockAddressUseCase {
	mock := &MockAddressUseCase{ctrl: ctrl}
	mock.recorder = &MockAddressUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddressUseCase) EXPECT() *MockAddressUseCaseMockRecorder {
	return m.recorder
}

// AddAddress mocks base method.
func (m *MockAddressUseCase) AddAddress(ctx context.Context, userID int, addr domain.Address) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAddress", ctx, userID, addr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAddress indicates an expected call of AddAddress.
func (mr *MockAddressUseCaseMockRecorder) AddAddress(ctx, userID, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAddress", reflect.TypeOf((*MockAddressUseCase)(nil).AddAddress), ctx, userID, addr)
}

// DeleteAddress mocks base method.
func (m *MockAddressUseCase) DeleteAddress(ctx context.Context, userID int, addressPublicID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddress", ctx, userID, addressPublicID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddress indicates an expected call of DeleteAddress.
func (mr *MockAddressUseCaseMockRecorder) DeleteAddress(ctx, userID, addressPublicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddress", reflect.TypeOf((*MockAddressUseCase)(nil).DeleteAddress), ctx, userID, addressPublicID)
}

// GetMyAddresses mocks base method.
func (m *MockAddressUseCase) GetMyAddresses(ctx context.Context, userID int) ([]domain.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyAddresses", ctx, userID)
	ret0, _ := ret[0].([]domain.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyAddresses indicates an expected call of GetMyAddresses.
func (mr *MockAddressUseCaseMockRecorder) GetMyAddresses(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyAddresses", reflect.TypeOf((*MockAddressUseCase)(nil).GetMyAddresses), ctx, userID)
}

// UpdateAddress mocks base method.
func (m *MockAddressUseCase) UpdateAddress(ctx context.Context, userID int, addr domain.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", ctx, userID, addr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockAddressUseCaseMockRecorder) UpdateAddress(ctx, userID, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockAddressUseCase)(nil).UpdateAddress), ctx, userID, addr)
}
