// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_NaNcats/internal/usecase (interfaces: CartUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/cart_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_NaNcats/internal/usecase CartUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_NaNcats/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCartUseCase is a mock of CartUseCase interface.
type MockCartUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCartUseCaseMockRecorder
	isgomock struct{}
}

// MockCartUseCaseMockRecorder is the mock recorder for MockCartUseCase.
type MockCartUseCaseMockRecorder struct {
	mock *MockCartUseCase
}

// NewMockCartUseCase creates a new mock instance.
func NewMockCartUseCase(ctrl *gomock.Controller) *MockCartUseCase {
	mock := &MockCartUseCase{ctrl: ctrl}
	mock.recorder = &MockCartUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartUseCase) EXPECT() *MockCartUseCaseMockRecorder {
	return m.recorder
}

// GetCart mocks base method.
func (m *MockCartUseCase) GetCart(ctx context.Context, userID int) (domain.Cart, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCart", ctx, userID)
	ret0, _ := ret[0].(domain.Cart)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCart indicates an expected call of GetCart.
func (mr *MockCartUseCaseMockRecorder) GetCart(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockCartUseCase)(nil).GetCart), ctx, userID)
}

// UpdateCart mocks base method.
func (m *MockCartUseCase) UpdateCart(ctx context.Context, userID int, cartData domain.Cart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCart", ctx, userID, cartData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCart indicates an expected call of UpdateCart.
func (mr *MockCartUseCaseMockRecorder) UpdateCart(ctx, userID, cartData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCart", reflect.TypeOf((*MockCartUseCase)(nil).UpdateCart), ctx, userID, cartData)
}
