// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_NaNcats/internal/usecase (interfaces: PaymentUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/payment_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_NaNcats/internal/usecase PaymentUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_NaNcats/internal/domain"
	yookassa "github.com/go-park-mail-ru/2026_1_NaNcats/pkg/api_clients/yookassa"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentUseCase is a mock of PaymentUseCase interface.
type MockPaymentUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentUseCaseMockRecorder
	isgomock struct{}
}

// MockPaymentUseCaseMockRecorder is the mock recorder for MockPaymentUseCase.
type MockPaymentUseCaseMockRecorder struct {
	mock *MockPaymentUseCase
}

// NewMockPaymentUseCase creates a new mock instance.
func NewMockPaymentUseCase(ctrl *gomock.Controller) *MockPaymentUseCase {
	mock := &MockPaymentUseCase{ctrl: ctrl}
	mock.recorder = &MockPaymentUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentUseCase) EXPECT() *MockPaymentUseCaseMockRecorder {
	return m.recorder
}

// DeleteCard mocks base method.
func (m *MockPaymentUseCase) DeleteCard(ctx context.Context, cardID string, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCard", ctx, cardID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCard indicates an expected call of DeleteCard.
func (mr *MockPaymentUseCaseMockRecorder) DeleteCard(ctx, cardID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCard", reflect.TypeOf((*MockPaymentUseCase)(nil).DeleteCard), ctx, cardID, userID)
}

// GetUserCards mocks base method.
func (m *MockPaymentUseCase) GetUserCards(ctx context.Context, userID int) ([]domain.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCards", ctx, userID)
	ret0, _ := ret[0].([]domain.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCards indicates an expected call of GetUserCards.
func (mr *MockPaymentUseCaseMockRecorder) GetUserCards(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCards", reflect.TypeOf((*MockPaymentUseCase)(nil).GetUserCards), ctx, userID)
}

// InitiateCardBinding mocks base method.
func (m *MockPaymentUseCase) InitiateCardBinding(ctx context.Context, userID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateCardBinding", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateCardBinding indicates an expected call of InitiateCardBinding.
func (mr *MockPaymentUseCaseMockRecorder) InitiateCardBinding(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateCardBinding", reflect.TypeOf((*MockPaymentUseCase)(nil).InitiateCardBinding), ctx, userID)
}

// ProcessPaymentMethodWebhook mocks base method.
func (m *MockPaymentUseCase) ProcessPaymentMethodWebhook(ctx context.Context, paymentMethod *yookassa.WebhookPaymentMethodObject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPaymentMethodWebhook", ctx, paymentMethod)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessPaymentMethodWebhook indicates an expected call of ProcessPaymentMethodWebhook.
func (mr *MockPaymentUseCaseMockRecorder) ProcessPaymentMethodWebhook(ctx, paymentMethod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPaymentMethodWebhook", reflect.TypeOf((*MockPaymentUseCase)(nil).ProcessPaymentMethodWebhook), ctx, paymentMethod)
}

// ProcessPaymentWebhook mocks base method.
func (m *MockPaymentUseCase) ProcessPaymentWebhook(ctx context.Context, payment *yookassa.WebhookPaymentObject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPaymentWebhook", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessPaymentWebhook indicates an expected call of ProcessPaymentWebhook.
func (mr *MockPaymentUseCaseMockRecorder) ProcessPaymentWebhook(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPaymentWebhook", reflect.TypeOf((*MockPaymentUseCase)(nil).ProcessPaymentWebhook), ctx, payment)
}

// SetDefaultCard mocks base method.
func (m *MockPaymentUseCase) SetDefaultCard(ctx context.Context, cardID string, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultCard", ctx, cardID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefaultCard indicates an expected call of SetDefaultCard.
func (mr *MockPaymentUseCaseMockRecorder) SetDefaultCard(ctx, cardID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultCard", reflect.TypeOf((*MockPaymentUseCase)(nil).SetDefaultCard), ctx, cardID, userID)
}
