// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../shared/templates/tracing.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package usecase

//go:generate gowrap gen -p github.com/go-park-mail-ru/2026_1_NaNcats/services/support/internal/usecase -i SupportUseCase -t ../../../../shared/templates/tracing.tmpl -o support_tracing_mw.go -v TracerName=support-service -l ""

import (
	"context"

	"github.com/go-park-mail-ru/2026_1_NaNcats/services/support/internal/domain"
	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
	otelcodes "go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

// SupportUseCaseTracingMiddleware реализует интерфейс SupportUseCase с поддержкой трассировки OpenTelemetry
type SupportUseCaseTracingMiddleware struct {
	next   SupportUseCase
	tracer trace.Tracer
}

// NewSupportUseCaseTracingMiddleware создает новый экземпляр декоратора для трассировки
func NewSupportUseCaseTracingMiddleware(next SupportUseCase) SupportUseCaseTracingMiddleware {
	return SupportUseCaseTracingMiddleware{
		next:   next,
		tracer: otel.Tracer("support-service"),
	}
}

// AddMessage трассирует выполнение метода AddMessage
func (m SupportUseCaseTracingMiddleware) AddMessage(ctx context.Context, ticketPublicID uuid.UUID, authorID *int64, authorRole string, text string, idempotencyKey string) (err error) {

	ctx, span := m.tracer.Start(ctx, "SupportUseCase.AddMessage")

	defer span.End()

	err = m.next.AddMessage(ctx, ticketPublicID, authorID, authorRole, text, idempotencyKey)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// ChangeTicketStatus трассирует выполнение метода ChangeTicketStatus
func (m SupportUseCaseTracingMiddleware) ChangeTicketStatus(ctx context.Context, ticketPublicID uuid.UUID, status string, agentID int64, idempotencyKey string) (err error) {

	ctx, span := m.tracer.Start(ctx, "SupportUseCase.ChangeTicketStatus")

	defer span.End()

	err = m.next.ChangeTicketStatus(ctx, ticketPublicID, status, agentID, idempotencyKey)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// CreateTicket трассирует выполнение метода CreateTicket
func (m SupportUseCaseTracingMiddleware) CreateTicket(ctx context.Context, input domain.CreateTicketInput) (u1 uuid.UUID, err error) {

	ctx, span := m.tracer.Start(ctx, "SupportUseCase.CreateTicket")

	defer span.End()

	u1, err = m.next.CreateTicket(ctx, input)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// GetAssignedTickets трассирует выполнение метода GetAssignedTickets
func (m SupportUseCaseTracingMiddleware) GetAssignedTickets(ctx context.Context, agentID int64) (ta1 []domain.Ticket, err error) {

	ctx, span := m.tracer.Start(ctx, "SupportUseCase.GetAssignedTickets")

	defer span.End()

	ta1, err = m.next.GetAssignedTickets(ctx, agentID)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// GetCategories трассирует выполнение метода GetCategories
func (m SupportUseCaseTracingMiddleware) GetCategories(ctx context.Context) (ca1 []domain.Category, err error) {

	ctx, span := m.tracer.Start(ctx, "SupportUseCase.GetCategories")

	defer span.End()

	ca1, err = m.next.GetCategories(ctx)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// GetMyTickets трассирует выполнение метода GetMyTickets
func (m SupportUseCaseTracingMiddleware) GetMyTickets(ctx context.Context, clientID *int64, guestID *uuid.UUID) (ta1 []domain.Ticket, err error) {

	ctx, span := m.tracer.Start(ctx, "SupportUseCase.GetMyTickets")

	defer span.End()

	ta1, err = m.next.GetMyTickets(ctx, clientID, guestID)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// GetStats трассирует выполнение метода GetStats
func (m SupportUseCaseTracingMiddleware) GetStats(ctx context.Context, agentID int64) (s1 domain.SupportStats, err error) {

	ctx, span := m.tracer.Start(ctx, "SupportUseCase.GetStats")

	defer span.End()

	s1, err = m.next.GetStats(ctx, agentID)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// GetTemplates трассирует выполнение метода GetTemplates
func (m SupportUseCaseTracingMiddleware) GetTemplates(ctx context.Context) (ta1 []domain.Template, err error) {

	ctx, span := m.tracer.Start(ctx, "SupportUseCase.GetTemplates")

	defer span.End()

	ta1, err = m.next.GetTemplates(ctx)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// GetTicketChat трассирует выполнение метода GetTicketChat
func (m SupportUseCaseTracingMiddleware) GetTicketChat(ctx context.Context, ticketPublicID uuid.UUID) (ea1 []domain.Event, err error) {

	ctx, span := m.tracer.Start(ctx, "SupportUseCase.GetTicketChat")

	defer span.End()

	ea1, err = m.next.GetTicketChat(ctx, ticketPublicID)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// GetTicketEvents трассирует выполнение метода GetTicketEvents
func (m SupportUseCaseTracingMiddleware) GetTicketEvents(ctx context.Context, publicID uuid.UUID, clientID *int64, guestID *uuid.UUID) (ea1 []domain.Event, err error) {

	ctx, span := m.tracer.Start(ctx, "SupportUseCase.GetTicketEvents")

	defer span.End()

	ea1, err = m.next.GetTicketEvents(ctx, publicID, clientID, guestID)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// RateTicket трассирует выполнение метода RateTicket
func (m SupportUseCaseTracingMiddleware) RateTicket(ctx context.Context, ticketPublicID uuid.UUID, rating int, authorID *int64, idempotencyKey string) (err error) {

	ctx, span := m.tracer.Start(ctx, "SupportUseCase.RateTicket")

	defer span.End()

	err = m.next.RateTicket(ctx, ticketPublicID, rating, authorID, idempotencyKey)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// ReassignTicket трассирует выполнение метода ReassignTicket
func (m SupportUseCaseTracingMiddleware) ReassignTicket(ctx context.Context, ticketPublicID uuid.UUID, agentID int64, line int, authorID int64, idempotencyKey string) (err error) {

	ctx, span := m.tracer.Start(ctx, "SupportUseCase.ReassignTicket")

	defer span.End()

	err = m.next.ReassignTicket(ctx, ticketPublicID, agentID, line, authorID, idempotencyKey)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// SetAgentStatus трассирует выполнение метода SetAgentStatus
func (m SupportUseCaseTracingMiddleware) SetAgentStatus(ctx context.Context, agentID int64, status string) (err error) {

	ctx, span := m.tracer.Start(ctx, "SupportUseCase.SetAgentStatus")

	defer span.End()

	err = m.next.SetAgentStatus(ctx, agentID, status)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}
