logger:
  level: "debug"

postgres:
  url: "postgres://user:password@localhost:5439/user_db?sslmode=disable"

grpc:
  port: "50052"
  timeout: "5s"

s3:
  key_id: "my_s3_key_id"
  secret_key: "my_s3_secret_key"
  bucket_name: "nancats-bucket"
  region: "ru-central1"

default_avatar_url: "https://nancats-bucket.storage.yandexcloud.net/avatars/default-avatar.webp"