// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_NaNcats/api-gateway/internal/grpc_client/cartclient (interfaces: CartClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/cart_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_NaNcats/api-gateway/internal/grpc_client/cartclient CartClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	cartclient "github.com/go-park-mail-ru/2026_1_NaNcats/api-gateway/internal/grpc_client/cartclient"
	gomock "go.uber.org/mock/gomock"
)

// MockCartClient is a mock of CartClient interface.
type MockCartClient struct {
	ctrl     *gomock.Controller
	recorder *MockCartClientMockRecorder
	isgomock struct{}
}

// MockCartClientMockRecorder is the mock recorder for MockCartClient.
type MockCartClientMockRecorder struct {
	mock *MockCartClient
}

// NewMockCartClient creates a new mock instance.
func NewMockCartClient(ctrl *gomock.Controller) *MockCartClient {
	mock := &MockCartClient{ctrl: ctrl}
	mock.recorder = &MockCartClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartClient) EXPECT() *MockCartClientMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockCartClient) AddItem(ctx context.Context, cartID string, userID, dishID int64, quantity int32, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, cartID, userID, dishID, quantity, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockCartClientMockRecorder) AddItem(ctx, cartID, userID, dishID, quantity, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockCartClient)(nil).AddItem), ctx, cartID, userID, dishID, quantity, idempotencyKey)
}

// ClearCart mocks base method.
func (m *MockCartClient) ClearCart(ctx context.Context, cartID string, userID int64, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCart", ctx, cartID, userID, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCart indicates an expected call of ClearCart.
func (mr *MockCartClientMockRecorder) ClearCart(ctx, cartID, userID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCart", reflect.TypeOf((*MockCartClient)(nil).ClearCart), ctx, cartID, userID, idempotencyKey)
}

// CloseSharedCart mocks base method.
func (m *MockCartClient) CloseSharedCart(ctx context.Context, cartID string, adminID int64, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSharedCart", ctx, cartID, adminID, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSharedCart indicates an expected call of CloseSharedCart.
func (mr *MockCartClientMockRecorder) CloseSharedCart(ctx, cartID, adminID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSharedCart", reflect.TypeOf((*MockCartClient)(nil).CloseSharedCart), ctx, cartID, adminID, idempotencyKey)
}

// GenerateInvite mocks base method.
func (m *MockCartClient) GenerateInvite(ctx context.Context, cartID string, adminID int64) (*cartclient.InviteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateInvite", ctx, cartID, adminID)
	ret0, _ := ret[0].(*cartclient.InviteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateInvite indicates an expected call of GenerateInvite.
func (mr *MockCartClientMockRecorder) GenerateInvite(ctx, cartID, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateInvite", reflect.TypeOf((*MockCartClient)(nil).GenerateInvite), ctx, cartID, adminID)
}

// GetCart mocks base method.
func (m *MockCartClient) GetCart(ctx context.Context, userID int64) (*cartclient.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCart", ctx, userID)
	ret0, _ := ret[0].(*cartclient.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCart indicates an expected call of GetCart.
func (mr *MockCartClientMockRecorder) GetCart(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockCartClient)(nil).GetCart), ctx, userID)
}

// JoinCart mocks base method.
func (m *MockCartClient) JoinCart(ctx context.Context, token string, userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinCart", ctx, token, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinCart indicates an expected call of JoinCart.
func (mr *MockCartClientMockRecorder) JoinCart(ctx, token, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinCart", reflect.TypeOf((*MockCartClient)(nil).JoinCart), ctx, token, userID)
}

// KickMember mocks base method.
func (m *MockCartClient) KickMember(ctx context.Context, cartID string, adminID, targetUserID int64, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KickMember", ctx, cartID, adminID, targetUserID, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// KickMember indicates an expected call of KickMember.
func (mr *MockCartClientMockRecorder) KickMember(ctx, cartID, adminID, targetUserID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KickMember", reflect.TypeOf((*MockCartClient)(nil).KickMember), ctx, cartID, adminID, targetUserID, idempotencyKey)
}

// LockCart mocks base method.
func (m *MockCartClient) LockCart(ctx context.Context, cartID string, userID int64, payForAll bool, payerMapping map[int64]int64, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockCart", ctx, cartID, userID, payForAll, payerMapping, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockCart indicates an expected call of LockCart.
func (mr *MockCartClientMockRecorder) LockCart(ctx, cartID, userID, payForAll, payerMapping, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockCart", reflect.TypeOf((*MockCartClient)(nil).LockCart), ctx, cartID, userID, payForAll, payerMapping, idempotencyKey)
}

// ReassignItemOwner mocks base method.
func (m *MockCartClient) ReassignItemOwner(ctx context.Context, cartID string, adminID, dishID int64, newOwnerID *int64, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignItemOwner", ctx, cartID, adminID, dishID, newOwnerID, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReassignItemOwner indicates an expected call of ReassignItemOwner.
func (mr *MockCartClientMockRecorder) ReassignItemOwner(ctx, cartID, adminID, dishID, newOwnerID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignItemOwner", reflect.TypeOf((*MockCartClient)(nil).ReassignItemOwner), ctx, cartID, adminID, dishID, newOwnerID, idempotencyKey)
}

// RemoveItem mocks base method.
func (m *MockCartClient) RemoveItem(ctx context.Context, cartID string, userID, dishID int64, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", ctx, cartID, userID, dishID, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockCartClientMockRecorder) RemoveItem(ctx, cartID, userID, dishID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockCartClient)(nil).RemoveItem), ctx, cartID, userID, dishID, idempotencyKey)
}

// UnlockCart mocks base method.
func (m *MockCartClient) UnlockCart(ctx context.Context, cartID string, userID int64, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockCart", ctx, cartID, userID, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockCart indicates an expected call of UnlockCart.
func (mr *MockCartClientMockRecorder) UnlockCart(ctx, cartID, userID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockCart", reflect.TypeOf((*MockCartClient)(nil).UnlockCart), ctx, cartID, userID, idempotencyKey)
}

// UpdateItemQuantity mocks base method.
func (m *MockCartClient) UpdateItemQuantity(ctx context.Context, cartID string, userID, dishID int64, quantity int32, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItemQuantity", ctx, cartID, userID, dishID, quantity, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItemQuantity indicates an expected call of UpdateItemQuantity.
func (mr *MockCartClientMockRecorder) UpdateItemQuantity(ctx, cartID, userID, dishID, quantity, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItemQuantity", reflect.TypeOf((*MockCartClient)(nil).UpdateItemQuantity), ctx, cartID, userID, dishID, quantity, idempotencyKey)
}
