// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package user

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson93bf1e34DecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpUser(in *jlexer.Lexer, out *AchievementsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]AchievementItem, 0, 0)
					} else {
						out.Items = []AchievementItem{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v1 AchievementItem
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Items = append(out.Items, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson93bf1e34EncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpUser(out *jwriter.Writer, in AchievementsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"items\":"
		out.RawString(prefix[1:])
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Items {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AchievementsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson93bf1e34EncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpUser(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AchievementsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson93bf1e34EncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpUser(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AchievementsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson93bf1e34DecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpUser(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AchievementsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson93bf1e34DecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpUser(l, v)
}
func easyjson93bf1e34DecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpUser1(in *jlexer.Lexer, out *AchievementItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "icon":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Icon = string(in.String())
			}
		case "earned":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Earned = bool(in.Bool())
			}
		case "awarded_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AwardedAt = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson93bf1e34EncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpUser1(out *jwriter.Writer, in AchievementItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"icon\":"
		out.RawString(prefix)
		out.String(string(in.Icon))
	}
	{
		const prefix string = ",\"earned\":"
		out.RawString(prefix)
		out.Bool(bool(in.Earned))
	}
	if in.AwardedAt != "" {
		const prefix string = ",\"awarded_at\":"
		out.RawString(prefix)
		out.String(string(in.AwardedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AchievementItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson93bf1e34EncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpUser1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AchievementItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson93bf1e34EncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpUser1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AchievementItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson93bf1e34DecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpUser1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AchievementItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson93bf1e34DecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpUser1(l, v)
}
