// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: restaurant/restaurant.proto

package restaurant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestaurantBrand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerProfileId int64                  `protobuf:"varint,2,opt,name=owner_profile_id,json=ownerProfileId,proto3" json:"owner_profile_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PromotionTier  int32                  `protobuf:"varint,5,opt,name=promotion_tier,json=promotionTier,proto3" json:"promotion_tier,omitempty"`
	LogoUrl        string                 `protobuf:"bytes,6,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RestaurantBrand) Reset() {
	*x = RestaurantBrand{}
	mi := &file_restaurant_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantBrand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantBrand) ProtoMessage() {}

func (x *RestaurantBrand) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantBrand.ProtoReflect.Descriptor instead.
func (*RestaurantBrand) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{0}
}

func (x *RestaurantBrand) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RestaurantBrand) GetOwnerProfileId() int64 {
	if x != nil {
		return x.OwnerProfileId
	}
	return 0
}

func (x *RestaurantBrand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestaurantBrand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RestaurantBrand) GetPromotionTier() int32 {
	if x != nil {
		return x.PromotionTier
	}
	return 0
}

func (x *RestaurantBrand) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

type Dish struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RestaurantBrandId int64                  `protobuf:"varint,2,opt,name=restaurant_brand_id,json=restaurantBrandId,proto3" json:"restaurant_brand_id,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price             int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl          string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Dish) Reset() {
	*x = Dish{}
	mi := &file_restaurant_restaurant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dish) ProtoMessage() {}

func (x *Dish) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dish.ProtoReflect.Descriptor instead.
func (*Dish) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{1}
}

func (x *Dish) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dish) GetRestaurantBrandId() int64 {
	if x != nil {
		return x.RestaurantBrandId
	}
	return 0
}

func (x *Dish) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dish) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Dish) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Dish) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type GetRestaurantBrandsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantBrandsListRequest) Reset() {
	*x = GetRestaurantBrandsListRequest{}
	mi := &file_restaurant_restaurant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantBrandsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantBrandsListRequest) ProtoMessage() {}

func (x *GetRestaurantBrandsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantBrandsListRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantBrandsListRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{2}
}

func (x *GetRestaurantBrandsListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRestaurantBrandsListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetRestaurantBrandsListResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RestaurantBrands []*RestaurantBrand     `protobuf:"bytes,1,rep,name=restaurant_brands,json=restaurantBrands,proto3" json:"restaurant_brands,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetRestaurantBrandsListResponse) Reset() {
	*x = GetRestaurantBrandsListResponse{}
	mi := &file_restaurant_restaurant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantBrandsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantBrandsListResponse) ProtoMessage() {}

func (x *GetRestaurantBrandsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantBrandsListResponse.ProtoReflect.Descriptor instead.
func (*GetRestaurantBrandsListResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{3}
}

func (x *GetRestaurantBrandsListResponse) GetRestaurantBrands() []*RestaurantBrand {
	if x != nil {
		return x.RestaurantBrands
	}
	return nil
}

type GetRestaurantBrandByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantBrandByIDRequest) Reset() {
	*x = GetRestaurantBrandByIDRequest{}
	mi := &file_restaurant_restaurant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantBrandByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantBrandByIDRequest) ProtoMessage() {}

func (x *GetRestaurantBrandByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantBrandByIDRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantBrandByIDRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{4}
}

func (x *GetRestaurantBrandByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRestaurantBrandByIDResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RestaurantBrand *RestaurantBrand       `protobuf:"bytes,1,opt,name=restaurant_brand,json=restaurantBrand,proto3" json:"restaurant_brand,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRestaurantBrandByIDResponse) Reset() {
	*x = GetRestaurantBrandByIDResponse{}
	mi := &file_restaurant_restaurant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantBrandByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantBrandByIDResponse) ProtoMessage() {}

func (x *GetRestaurantBrandByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantBrandByIDResponse.ProtoReflect.Descriptor instead.
func (*GetRestaurantBrandByIDResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{5}
}

func (x *GetRestaurantBrandByIDResponse) GetRestaurantBrand() *RestaurantBrand {
	if x != nil {
		return x.RestaurantBrand
	}
	return nil
}

type GetRestaurantBrandsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandIds      []int64                `protobuf:"varint,1,rep,packed,name=brand_ids,json=brandIds,proto3" json:"brand_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantBrandsByIDsRequest) Reset() {
	*x = GetRestaurantBrandsByIDsRequest{}
	mi := &file_restaurant_restaurant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantBrandsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantBrandsByIDsRequest) ProtoMessage() {}

func (x *GetRestaurantBrandsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantBrandsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantBrandsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{6}
}

func (x *GetRestaurantBrandsByIDsRequest) GetBrandIds() []int64 {
	if x != nil {
		return x.BrandIds
	}
	return nil
}

type GetRestaurantBrandsByIDsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RestaurantBrands []*RestaurantBrand     `protobuf:"bytes,1,rep,name=restaurant_brands,json=restaurantBrands,proto3" json:"restaurant_brands,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetRestaurantBrandsByIDsResponse) Reset() {
	*x = GetRestaurantBrandsByIDsResponse{}
	mi := &file_restaurant_restaurant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantBrandsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantBrandsByIDsResponse) ProtoMessage() {}

func (x *GetRestaurantBrandsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantBrandsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetRestaurantBrandsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{7}
}

func (x *GetRestaurantBrandsByIDsResponse) GetRestaurantBrands() []*RestaurantBrand {
	if x != nil {
		return x.RestaurantBrands
	}
	return nil
}

type GetDishesByRestaurantBrandIDRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RestaurantBrandId int64                  `protobuf:"varint,1,opt,name=restaurant_brand_id,json=restaurantBrandId,proto3" json:"restaurant_brand_id,omitempty"`
	Limit             int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset            int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetDishesByRestaurantBrandIDRequest) Reset() {
	*x = GetDishesByRestaurantBrandIDRequest{}
	mi := &file_restaurant_restaurant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishesByRestaurantBrandIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesByRestaurantBrandIDRequest) ProtoMessage() {}

func (x *GetDishesByRestaurantBrandIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesByRestaurantBrandIDRequest.ProtoReflect.Descriptor instead.
func (*GetDishesByRestaurantBrandIDRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{8}
}

func (x *GetDishesByRestaurantBrandIDRequest) GetRestaurantBrandId() int64 {
	if x != nil {
		return x.RestaurantBrandId
	}
	return 0
}

func (x *GetDishesByRestaurantBrandIDRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetDishesByRestaurantBrandIDRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetDishesByRestaurantBrandIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dishes        []*Dish                `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDishesByRestaurantBrandIDResponse) Reset() {
	*x = GetDishesByRestaurantBrandIDResponse{}
	mi := &file_restaurant_restaurant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishesByRestaurantBrandIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesByRestaurantBrandIDResponse) ProtoMessage() {}

func (x *GetDishesByRestaurantBrandIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesByRestaurantBrandIDResponse.ProtoReflect.Descriptor instead.
func (*GetDishesByRestaurantBrandIDResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{9}
}

func (x *GetDishesByRestaurantBrandIDResponse) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

type GetDishesByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishIds       []int64                `protobuf:"varint,1,rep,packed,name=dish_ids,json=dishIds,proto3" json:"dish_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDishesByIDsRequest) Reset() {
	*x = GetDishesByIDsRequest{}
	mi := &file_restaurant_restaurant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishesByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesByIDsRequest) ProtoMessage() {}

func (x *GetDishesByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetDishesByIDsRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{10}
}

func (x *GetDishesByIDsRequest) GetDishIds() []int64 {
	if x != nil {
		return x.DishIds
	}
	return nil
}

type GetDishesByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dishes        []*Dish                `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDishesByIDsResponse) Reset() {
	*x = GetDishesByIDsResponse{}
	mi := &file_restaurant_restaurant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDishesByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesByIDsResponse) ProtoMessage() {}

func (x *GetDishesByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_restaurant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetDishesByIDsResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_restaurant_proto_rawDescGZIP(), []int{11}
}

func (x *GetDishesByIDsResponse) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

var File_restaurant_restaurant_proto protoreflect.FileDescriptor

const file_restaurant_restaurant_proto_rawDesc = "" +
	"\n" +
	"\x1brestaurant/restaurant.proto\x12\n" +
	"restaurant\"\xc3\x01\n" +
	"\x0fRestaurantBrand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12(\n" +
	"\x10owner_profile_id\x18\x02 \x01(\x03R\x0eownerProfileId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12%\n" +
	"\x0epromotion_tier\x18\x05 \x01(\x05R\rpromotionTier\x12\x19\n" +
	"\blogo_url\x18\x06 \x01(\tR\alogoUrl\"\xaf\x01\n" +
	"\x04Dish\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\x13restaurant_brand_id\x18\x02 \x01(\x03R\x11restaurantBrandId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\"N\n" +
	"\x1eGetRestaurantBrandsListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"k\n" +
	"\x1fGetRestaurantBrandsListResponse\x12H\n" +
	"\x11restaurant_brands\x18\x01 \x03(\v2\x1b.restaurant.RestaurantBrandR\x10restaurantBrands\"/\n" +
	"\x1dGetRestaurantBrandByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"h\n" +
	"\x1eGetRestaurantBrandByIDResponse\x12F\n" +
	"\x10restaurant_brand\x18\x01 \x01(\v2\x1b.restaurant.RestaurantBrandR\x0frestaurantBrand\">\n" +
	"\x1fGetRestaurantBrandsByIDsRequest\x12\x1b\n" +
	"\tbrand_ids\x18\x01 \x03(\x03R\bbrandIds\"l\n" +
	" GetRestaurantBrandsByIDsResponse\x12H\n" +
	"\x11restaurant_brands\x18\x01 \x03(\v2\x1b.restaurant.RestaurantBrandR\x10restaurantBrands\"\x83\x01\n" +
	"#GetDishesByRestaurantBrandIDRequest\x12.\n" +
	"\x13restaurant_brand_id\x18\x01 \x01(\x03R\x11restaurantBrandId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"P\n" +
	"$GetDishesByRestaurantBrandIDResponse\x12(\n" +
	"\x06dishes\x18\x01 \x03(\v2\x10.restaurant.DishR\x06dishes\"2\n" +
	"\x15GetDishesByIDsRequest\x12\x19\n" +
	"\bdish_ids\x18\x01 \x03(\x03R\adishIds\"B\n" +
	"\x16GetDishesByIDsResponse\x12(\n" +
	"\x06dishes\x18\x01 \x03(\v2\x10.restaurant.DishR\x06dishes2\xcc\x04\n" +
	"\x11RestaurantService\x12r\n" +
	"\x17GetRestaurantBrandsList\x12*.restaurant.GetRestaurantBrandsListRequest\x1a+.restaurant.GetRestaurantBrandsListResponse\x12o\n" +
	"\x16GetRestaurantBrandByID\x12).restaurant.GetRestaurantBrandByIDRequest\x1a*.restaurant.GetRestaurantBrandByIDResponse\x12u\n" +
	"\x18GetRestaurantBrandsByIDs\x12+.restaurant.GetRestaurantBrandsByIDsRequest\x1a,.restaurant.GetRestaurantBrandsByIDsResponse\x12\x81\x01\n" +
	"\x1cGetDishesByRestaurantBrandID\x12/.restaurant.GetDishesByRestaurantBrandIDRequest\x1a0.restaurant.GetDishesByRestaurantBrandIDResponse\x12W\n" +
	"\x0eGetDishesByIDs\x12!.restaurant.GetDishesByIDsRequest\x1a\".restaurant.GetDishesByIDsResponseBCZAgithub.com/go-park-mail-ru/2026_1_NaNcats/shared/proto/restaurantb\x06proto3"

var (
	file_restaurant_restaurant_proto_rawDescOnce sync.Once
	file_restaurant_restaurant_proto_rawDescData []byte
)

func file_restaurant_restaurant_proto_rawDescGZIP() []byte {
	file_restaurant_restaurant_proto_rawDescOnce.Do(func() {
		file_restaurant_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_restaurant_restaurant_proto_rawDesc), len(file_restaurant_restaurant_proto_rawDesc)))
	})
	return file_restaurant_restaurant_proto_rawDescData
}

var file_restaurant_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_restaurant_restaurant_proto_goTypes = []any{
	(*RestaurantBrand)(nil),                      // 0: restaurant.RestaurantBrand
	(*Dish)(nil),                                 // 1: restaurant.Dish
	(*GetRestaurantBrandsListRequest)(nil),       // 2: restaurant.GetRestaurantBrandsListRequest
	(*GetRestaurantBrandsListResponse)(nil),      // 3: restaurant.GetRestaurantBrandsListResponse
	(*GetRestaurantBrandByIDRequest)(nil),        // 4: restaurant.GetRestaurantBrandByIDRequest
	(*GetRestaurantBrandByIDResponse)(nil),       // 5: restaurant.GetRestaurantBrandByIDResponse
	(*GetRestaurantBrandsByIDsRequest)(nil),      // 6: restaurant.GetRestaurantBrandsByIDsRequest
	(*GetRestaurantBrandsByIDsResponse)(nil),     // 7: restaurant.GetRestaurantBrandsByIDsResponse
	(*GetDishesByRestaurantBrandIDRequest)(nil),  // 8: restaurant.GetDishesByRestaurantBrandIDRequest
	(*GetDishesByRestaurantBrandIDResponse)(nil), // 9: restaurant.GetDishesByRestaurantBrandIDResponse
	(*GetDishesByIDsRequest)(nil),                // 10: restaurant.GetDishesByIDsRequest
	(*GetDishesByIDsResponse)(nil),               // 11: restaurant.GetDishesByIDsResponse
}
var file_restaurant_restaurant_proto_depIdxs = []int32{
	0,  // 0: restaurant.GetRestaurantBrandsListResponse.restaurant_brands:type_name -> restaurant.RestaurantBrand
	0,  // 1: restaurant.GetRestaurantBrandByIDResponse.restaurant_brand:type_name -> restaurant.RestaurantBrand
	0,  // 2: restaurant.GetRestaurantBrandsByIDsResponse.restaurant_brands:type_name -> restaurant.RestaurantBrand
	1,  // 3: restaurant.GetDishesByRestaurantBrandIDResponse.dishes:type_name -> restaurant.Dish
	1,  // 4: restaurant.GetDishesByIDsResponse.dishes:type_name -> restaurant.Dish
	2,  // 5: restaurant.RestaurantService.GetRestaurantBrandsList:input_type -> restaurant.GetRestaurantBrandsListRequest
	4,  // 6: restaurant.RestaurantService.GetRestaurantBrandByID:input_type -> restaurant.GetRestaurantBrandByIDRequest
	6,  // 7: restaurant.RestaurantService.GetRestaurantBrandsByIDs:input_type -> restaurant.GetRestaurantBrandsByIDsRequest
	8,  // 8: restaurant.RestaurantService.GetDishesByRestaurantBrandID:input_type -> restaurant.GetDishesByRestaurantBrandIDRequest
	10, // 9: restaurant.RestaurantService.GetDishesByIDs:input_type -> restaurant.GetDishesByIDsRequest
	3,  // 10: restaurant.RestaurantService.GetRestaurantBrandsList:output_type -> restaurant.GetRestaurantBrandsListResponse
	5,  // 11: restaurant.RestaurantService.GetRestaurantBrandByID:output_type -> restaurant.GetRestaurantBrandByIDResponse
	7,  // 12: restaurant.RestaurantService.GetRestaurantBrandsByIDs:output_type -> restaurant.GetRestaurantBrandsByIDsResponse
	9,  // 13: restaurant.RestaurantService.GetDishesByRestaurantBrandID:output_type -> restaurant.GetDishesByRestaurantBrandIDResponse
	11, // 14: restaurant.RestaurantService.GetDishesByIDs:output_type -> restaurant.GetDishesByIDsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_restaurant_restaurant_proto_init() }
func file_restaurant_restaurant_proto_init() {
	if File_restaurant_restaurant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_restaurant_restaurant_proto_rawDesc), len(file_restaurant_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restaurant_restaurant_proto_goTypes,
		DependencyIndexes: file_restaurant_restaurant_proto_depIdxs,
		MessageInfos:      file_restaurant_restaurant_proto_msgTypes,
	}.Build()
	File_restaurant_restaurant_proto = out.File
	file_restaurant_restaurant_proto_goTypes = nil
	file_restaurant_restaurant_proto_depIdxs = nil
}
