// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: restaurant/restaurant.proto

package restaurant

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RestaurantService_GetRestaurantBrandsList_FullMethodName      = "/restaurant.RestaurantService/GetRestaurantBrandsList"
	RestaurantService_GetRestaurantBrandByID_FullMethodName       = "/restaurant.RestaurantService/GetRestaurantBrandByID"
	RestaurantService_GetRestaurantBrandsByIDs_FullMethodName     = "/restaurant.RestaurantService/GetRestaurantBrandsByIDs"
	RestaurantService_GetDishesByRestaurantBrandID_FullMethodName = "/restaurant.RestaurantService/GetDishesByRestaurantBrandID"
	RestaurantService_GetDishesByIDs_FullMethodName               = "/restaurant.RestaurantService/GetDishesByIDs"
	RestaurantService_CreateRestaurantBrand_FullMethodName        = "/restaurant.RestaurantService/CreateRestaurantBrand"
	RestaurantService_UpdateRestaurantBrand_FullMethodName        = "/restaurant.RestaurantService/UpdateRestaurantBrand"
	RestaurantService_DeleteRestaurantBrand_FullMethodName        = "/restaurant.RestaurantService/DeleteRestaurantBrand"
	RestaurantService_CreateDish_FullMethodName                   = "/restaurant.RestaurantService/CreateDish"
	RestaurantService_UpdateDish_FullMethodName                   = "/restaurant.RestaurantService/UpdateDish"
	RestaurantService_DeleteDish_FullMethodName                   = "/restaurant.RestaurantService/DeleteDish"
)

// RestaurantServiceClient is the client API for RestaurantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Микросервис каталога (Рестораны и Блюда)
type RestaurantServiceClient interface {
	// Метод получения списка ресторанов
	GetRestaurantBrandsList(ctx context.Context, in *GetRestaurantBrandsListRequest, opts ...grpc.CallOption) (*GetRestaurantBrandsListResponse, error)
	// Метод получения ресторана по ID
	GetRestaurantBrandByID(ctx context.Context, in *GetRestaurantBrandByIDRequest, opts ...grpc.CallOption) (*GetRestaurantBrandByIDResponse, error)
	// Метод пакетного получения данных о ресторанах
	GetRestaurantBrandsByIDs(ctx context.Context, in *GetRestaurantBrandsByIDsRequest, opts ...grpc.CallOption) (*GetRestaurantBrandsByIDsResponse, error)
	// Метод получения блюд из ресторана по его ID
	GetDishesByRestaurantBrandID(ctx context.Context, in *GetDishesByRestaurantBrandIDRequest, opts ...grpc.CallOption) (*GetDishesByRestaurantBrandIDResponse, error)
	// Метод получения блюд по их ID
	GetDishesByIDs(ctx context.Context, in *GetDishesByIDsRequest, opts ...grpc.CallOption) (*GetDishesByIDsResponse, error)
	// Управление ресторанами (Админы)
	CreateRestaurantBrand(ctx context.Context, in *CreateBrandRequest, opts ...grpc.CallOption) (*RestaurantBrand, error)
	UpdateRestaurantBrand(ctx context.Context, in *UpdateBrandRequest, opts ...grpc.CallOption) (*RestaurantBrand, error)
	DeleteRestaurantBrand(ctx context.Context, in *DeleteBrandRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Управление блюдами (Админы/Овнеры)
	CreateDish(ctx context.Context, in *CreateDishRequest, opts ...grpc.CallOption) (*Dish, error)
	UpdateDish(ctx context.Context, in *UpdateDishRequest, opts ...grpc.CallOption) (*Dish, error)
	DeleteDish(ctx context.Context, in *DeleteDishRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type restaurantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestaurantServiceClient(cc grpc.ClientConnInterface) RestaurantServiceClient {
	return &restaurantServiceClient{cc}
}

func (c *restaurantServiceClient) GetRestaurantBrandsList(ctx context.Context, in *GetRestaurantBrandsListRequest, opts ...grpc.CallOption) (*GetRestaurantBrandsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRestaurantBrandsListResponse)
	err := c.cc.Invoke(ctx, RestaurantService_GetRestaurantBrandsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) GetRestaurantBrandByID(ctx context.Context, in *GetRestaurantBrandByIDRequest, opts ...grpc.CallOption) (*GetRestaurantBrandByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRestaurantBrandByIDResponse)
	err := c.cc.Invoke(ctx, RestaurantService_GetRestaurantBrandByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) GetRestaurantBrandsByIDs(ctx context.Context, in *GetRestaurantBrandsByIDsRequest, opts ...grpc.CallOption) (*GetRestaurantBrandsByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRestaurantBrandsByIDsResponse)
	err := c.cc.Invoke(ctx, RestaurantService_GetRestaurantBrandsByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) GetDishesByRestaurantBrandID(ctx context.Context, in *GetDishesByRestaurantBrandIDRequest, opts ...grpc.CallOption) (*GetDishesByRestaurantBrandIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDishesByRestaurantBrandIDResponse)
	err := c.cc.Invoke(ctx, RestaurantService_GetDishesByRestaurantBrandID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) GetDishesByIDs(ctx context.Context, in *GetDishesByIDsRequest, opts ...grpc.CallOption) (*GetDishesByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDishesByIDsResponse)
	err := c.cc.Invoke(ctx, RestaurantService_GetDishesByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) CreateRestaurantBrand(ctx context.Context, in *CreateBrandRequest, opts ...grpc.CallOption) (*RestaurantBrand, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestaurantBrand)
	err := c.cc.Invoke(ctx, RestaurantService_CreateRestaurantBrand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) UpdateRestaurantBrand(ctx context.Context, in *UpdateBrandRequest, opts ...grpc.CallOption) (*RestaurantBrand, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestaurantBrand)
	err := c.cc.Invoke(ctx, RestaurantService_UpdateRestaurantBrand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) DeleteRestaurantBrand(ctx context.Context, in *DeleteBrandRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RestaurantService_DeleteRestaurantBrand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) CreateDish(ctx context.Context, in *CreateDishRequest, opts ...grpc.CallOption) (*Dish, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Dish)
	err := c.cc.Invoke(ctx, RestaurantService_CreateDish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) UpdateDish(ctx context.Context, in *UpdateDishRequest, opts ...grpc.CallOption) (*Dish, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Dish)
	err := c.cc.Invoke(ctx, RestaurantService_UpdateDish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) DeleteDish(ctx context.Context, in *DeleteDishRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RestaurantService_DeleteDish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantServiceServer is the server API for RestaurantService service.
// All implementations must embed UnimplementedRestaurantServiceServer
// for forward compatibility.
//
// Микросервис каталога (Рестораны и Блюда)
type RestaurantServiceServer interface {
	// Метод получения списка ресторанов
	GetRestaurantBrandsList(context.Context, *GetRestaurantBrandsListRequest) (*GetRestaurantBrandsListResponse, error)
	// Метод получения ресторана по ID
	GetRestaurantBrandByID(context.Context, *GetRestaurantBrandByIDRequest) (*GetRestaurantBrandByIDResponse, error)
	// Метод пакетного получения данных о ресторанах
	GetRestaurantBrandsByIDs(context.Context, *GetRestaurantBrandsByIDsRequest) (*GetRestaurantBrandsByIDsResponse, error)
	// Метод получения блюд из ресторана по его ID
	GetDishesByRestaurantBrandID(context.Context, *GetDishesByRestaurantBrandIDRequest) (*GetDishesByRestaurantBrandIDResponse, error)
	// Метод получения блюд по их ID
	GetDishesByIDs(context.Context, *GetDishesByIDsRequest) (*GetDishesByIDsResponse, error)
	// Управление ресторанами (Админы)
	CreateRestaurantBrand(context.Context, *CreateBrandRequest) (*RestaurantBrand, error)
	UpdateRestaurantBrand(context.Context, *UpdateBrandRequest) (*RestaurantBrand, error)
	DeleteRestaurantBrand(context.Context, *DeleteBrandRequest) (*emptypb.Empty, error)
	// Управление блюдами (Админы/Овнеры)
	CreateDish(context.Context, *CreateDishRequest) (*Dish, error)
	UpdateDish(context.Context, *UpdateDishRequest) (*Dish, error)
	DeleteDish(context.Context, *DeleteDishRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedRestaurantServiceServer()
}

// UnimplementedRestaurantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRestaurantServiceServer struct{}

func (UnimplementedRestaurantServiceServer) GetRestaurantBrandsList(context.Context, *GetRestaurantBrandsListRequest) (*GetRestaurantBrandsListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRestaurantBrandsList not implemented")
}
func (UnimplementedRestaurantServiceServer) GetRestaurantBrandByID(context.Context, *GetRestaurantBrandByIDRequest) (*GetRestaurantBrandByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRestaurantBrandByID not implemented")
}
func (UnimplementedRestaurantServiceServer) GetRestaurantBrandsByIDs(context.Context, *GetRestaurantBrandsByIDsRequest) (*GetRestaurantBrandsByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRestaurantBrandsByIDs not implemented")
}
func (UnimplementedRestaurantServiceServer) GetDishesByRestaurantBrandID(context.Context, *GetDishesByRestaurantBrandIDRequest) (*GetDishesByRestaurantBrandIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDishesByRestaurantBrandID not implemented")
}
func (UnimplementedRestaurantServiceServer) GetDishesByIDs(context.Context, *GetDishesByIDsRequest) (*GetDishesByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDishesByIDs not implemented")
}
func (UnimplementedRestaurantServiceServer) CreateRestaurantBrand(context.Context, *CreateBrandRequest) (*RestaurantBrand, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRestaurantBrand not implemented")
}
func (UnimplementedRestaurantServiceServer) UpdateRestaurantBrand(context.Context, *UpdateBrandRequest) (*RestaurantBrand, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRestaurantBrand not implemented")
}
func (UnimplementedRestaurantServiceServer) DeleteRestaurantBrand(context.Context, *DeleteBrandRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRestaurantBrand not implemented")
}
func (UnimplementedRestaurantServiceServer) CreateDish(context.Context, *CreateDishRequest) (*Dish, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDish not implemented")
}
func (UnimplementedRestaurantServiceServer) UpdateDish(context.Context, *UpdateDishRequest) (*Dish, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDish not implemented")
}
func (UnimplementedRestaurantServiceServer) DeleteDish(context.Context, *DeleteDishRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDish not implemented")
}
func (UnimplementedRestaurantServiceServer) mustEmbedUnimplementedRestaurantServiceServer() {}
func (UnimplementedRestaurantServiceServer) testEmbeddedByValue()                           {}

// UnsafeRestaurantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestaurantServiceServer will
// result in compilation errors.
type UnsafeRestaurantServiceServer interface {
	mustEmbedUnimplementedRestaurantServiceServer()
}

func RegisterRestaurantServiceServer(s grpc.ServiceRegistrar, srv RestaurantServiceServer) {
	// If the following call panics, it indicates UnimplementedRestaurantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RestaurantService_ServiceDesc, srv)
}

func _RestaurantService_GetRestaurantBrandsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantBrandsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetRestaurantBrandsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_GetRestaurantBrandsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetRestaurantBrandsList(ctx, req.(*GetRestaurantBrandsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_GetRestaurantBrandByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantBrandByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetRestaurantBrandByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_GetRestaurantBrandByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetRestaurantBrandByID(ctx, req.(*GetRestaurantBrandByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_GetRestaurantBrandsByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantBrandsByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetRestaurantBrandsByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_GetRestaurantBrandsByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetRestaurantBrandsByIDs(ctx, req.(*GetRestaurantBrandsByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_GetDishesByRestaurantBrandID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDishesByRestaurantBrandIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetDishesByRestaurantBrandID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_GetDishesByRestaurantBrandID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetDishesByRestaurantBrandID(ctx, req.(*GetDishesByRestaurantBrandIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_GetDishesByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDishesByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetDishesByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_GetDishesByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetDishesByIDs(ctx, req.(*GetDishesByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_CreateRestaurantBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).CreateRestaurantBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_CreateRestaurantBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).CreateRestaurantBrand(ctx, req.(*CreateBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_UpdateRestaurantBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).UpdateRestaurantBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_UpdateRestaurantBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).UpdateRestaurantBrand(ctx, req.(*UpdateBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_DeleteRestaurantBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).DeleteRestaurantBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_DeleteRestaurantBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).DeleteRestaurantBrand(ctx, req.(*DeleteBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_CreateDish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).CreateDish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_CreateDish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).CreateDish(ctx, req.(*CreateDishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_UpdateDish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).UpdateDish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_UpdateDish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).UpdateDish(ctx, req.(*UpdateDishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_DeleteDish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).DeleteDish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_DeleteDish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).DeleteDish(ctx, req.(*DeleteDishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RestaurantService_ServiceDesc is the grpc.ServiceDesc for RestaurantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestaurantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "restaurant.RestaurantService",
	HandlerType: (*RestaurantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRestaurantBrandsList",
			Handler:    _RestaurantService_GetRestaurantBrandsList_Handler,
		},
		{
			MethodName: "GetRestaurantBrandByID",
			Handler:    _RestaurantService_GetRestaurantBrandByID_Handler,
		},
		{
			MethodName: "GetRestaurantBrandsByIDs",
			Handler:    _RestaurantService_GetRestaurantBrandsByIDs_Handler,
		},
		{
			MethodName: "GetDishesByRestaurantBrandID",
			Handler:    _RestaurantService_GetDishesByRestaurantBrandID_Handler,
		},
		{
			MethodName: "GetDishesByIDs",
			Handler:    _RestaurantService_GetDishesByIDs_Handler,
		},
		{
			MethodName: "CreateRestaurantBrand",
			Handler:    _RestaurantService_CreateRestaurantBrand_Handler,
		},
		{
			MethodName: "UpdateRestaurantBrand",
			Handler:    _RestaurantService_UpdateRestaurantBrand_Handler,
		},
		{
			MethodName: "DeleteRestaurantBrand",
			Handler:    _RestaurantService_DeleteRestaurantBrand_Handler,
		},
		{
			MethodName: "CreateDish",
			Handler:    _RestaurantService_CreateDish_Handler,
		},
		{
			MethodName: "UpdateDish",
			Handler:    _RestaurantService_UpdateDish_Handler,
		},
		{
			MethodName: "DeleteDish",
			Handler:    _RestaurantService_DeleteDish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "restaurant/restaurant.proto",
}
