// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  order

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( CreateOrderRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CreateOrderRequest ) UnmarshalJSON([]byte) error { return nil }
func ( CreateOrderRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CreateOrderRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CreateOrderRequest *CreateOrderRequest

func ( CreateOrderResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CreateOrderResponse ) UnmarshalJSON([]byte) error { return nil }
func ( CreateOrderResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CreateOrderResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CreateOrderResponse *CreateOrderResponse

func ( OrderHistoryResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* OrderHistoryResponse ) UnmarshalJSON([]byte) error { return nil }
func ( OrderHistoryResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* OrderHistoryResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_OrderHistoryResponse *OrderHistoryResponse
