// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_NaNcats/services/address/internal/repository (interfaces: AddressRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/address_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_NaNcats/services/address/internal/repository AddressRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_NaNcats/services/address/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAddressRepository is a mock of AddressRepository interface.
type MockAddressRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAddressRepositoryMockRecorder
	isgomock struct{}
}

// MockAddressRepositoryMockRecorder is the mock recorder for MockAddressRepository.
type MockAddressRepositoryMockRecorder struct {
	mock *MockAddressRepository
}

// NewMockAddressRepository creates a new mock instance.
func NewMockAddressRepository(ctrl *gomock.Controller) *MockAddressRepository {
	mock := &MockAddressRepository{ctrl: ctrl}
	mock.recorder = &MockAddressRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddressRepository) EXPECT() *MockAddressRepositoryMockRecorder {
	return m.recorder
}

// CreateAddress mocks base method.
func (m *MockAddressRepository) CreateAddress(ctx context.Context, userID int64, addr domain.Address, idempotencyKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddress", ctx, userID, addr, idempotencyKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAddress indicates an expected call of CreateAddress.
func (mr *MockAddressRepositoryMockRecorder) CreateAddress(ctx, userID, addr, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddress", reflect.TypeOf((*MockAddressRepository)(nil).CreateAddress), ctx, userID, addr, idempotencyKey)
}

// DeleteAddress mocks base method.
func (m *MockAddressRepository) DeleteAddress(ctx context.Context, userID int64, publicID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddress", ctx, userID, publicID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddress indicates an expected call of DeleteAddress.
func (mr *MockAddressRepositoryMockRecorder) DeleteAddress(ctx, userID, publicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddress", reflect.TypeOf((*MockAddressRepository)(nil).DeleteAddress), ctx, userID, publicID)
}

// GetAddressesByUserID mocks base method.
func (m *MockAddressRepository) GetAddressesByUserID(ctx context.Context, userID int64) ([]domain.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddressesByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddressesByUserID indicates an expected call of GetAddressesByUserID.
func (mr *MockAddressRepositoryMockRecorder) GetAddressesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressesByUserID", reflect.TypeOf((*MockAddressRepository)(nil).GetAddressesByUserID), ctx, userID)
}

// GetInternalIDByPublicID mocks base method.
func (m *MockAddressRepository) GetInternalIDByPublicID(ctx context.Context, userID int64, publicID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInternalIDByPublicID", ctx, userID, publicID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInternalIDByPublicID indicates an expected call of GetInternalIDByPublicID.
func (mr *MockAddressRepositoryMockRecorder) GetInternalIDByPublicID(ctx, userID, publicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInternalIDByPublicID", reflect.TypeOf((*MockAddressRepository)(nil).GetInternalIDByPublicID), ctx, userID, publicID)
}

// UpdateAddress mocks base method.
func (m *MockAddressRepository) UpdateAddress(ctx context.Context, userID int64, addr domain.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", ctx, userID, addr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockAddressRepositoryMockRecorder) UpdateAddress(ctx, userID, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockAddressRepository)(nil).UpdateAddress), ctx, userID, addr)
}
