// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: user/game.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WordleService_GetDailyWordleState_FullMethodName = "/user.WordleService/GetDailyWordleState"
	WordleService_MakeWordleGuess_FullMethodName     = "/user.WordleService/MakeWordleGuess"
)

// WordleServiceClient is the client API for WordleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Микросервис игры (Модуль внутри User)
type WordleServiceClient interface {
	// Метод получения текущего состояния игры за сегодня
	GetDailyWordleState(ctx context.Context, in *GetDailyWordleStateRequest, opts ...grpc.CallOption) (*GetDailyWordleStateResponse, error)
	// Метод применения попытки (угадывание слова)
	MakeWordleGuess(ctx context.Context, in *MakeWordleGuessRequest, opts ...grpc.CallOption) (*MakeWordleGuessResponse, error)
}

type wordleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWordleServiceClient(cc grpc.ClientConnInterface) WordleServiceClient {
	return &wordleServiceClient{cc}
}

func (c *wordleServiceClient) GetDailyWordleState(ctx context.Context, in *GetDailyWordleStateRequest, opts ...grpc.CallOption) (*GetDailyWordleStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyWordleStateResponse)
	err := c.cc.Invoke(ctx, WordleService_GetDailyWordleState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordleServiceClient) MakeWordleGuess(ctx context.Context, in *MakeWordleGuessRequest, opts ...grpc.CallOption) (*MakeWordleGuessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakeWordleGuessResponse)
	err := c.cc.Invoke(ctx, WordleService_MakeWordleGuess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordleServiceServer is the server API for WordleService service.
// All implementations must embed UnimplementedWordleServiceServer
// for forward compatibility.
//
// Микросервис игры (Модуль внутри User)
type WordleServiceServer interface {
	// Метод получения текущего состояния игры за сегодня
	GetDailyWordleState(context.Context, *GetDailyWordleStateRequest) (*GetDailyWordleStateResponse, error)
	// Метод применения попытки (угадывание слова)
	MakeWordleGuess(context.Context, *MakeWordleGuessRequest) (*MakeWordleGuessResponse, error)
	mustEmbedUnimplementedWordleServiceServer()
}

// UnimplementedWordleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWordleServiceServer struct{}

func (UnimplementedWordleServiceServer) GetDailyWordleState(context.Context, *GetDailyWordleStateRequest) (*GetDailyWordleStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailyWordleState not implemented")
}
func (UnimplementedWordleServiceServer) MakeWordleGuess(context.Context, *MakeWordleGuessRequest) (*MakeWordleGuessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MakeWordleGuess not implemented")
}
func (UnimplementedWordleServiceServer) mustEmbedUnimplementedWordleServiceServer() {}
func (UnimplementedWordleServiceServer) testEmbeddedByValue()                       {}

// UnsafeWordleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WordleServiceServer will
// result in compilation errors.
type UnsafeWordleServiceServer interface {
	mustEmbedUnimplementedWordleServiceServer()
}

func RegisterWordleServiceServer(s grpc.ServiceRegistrar, srv WordleServiceServer) {
	// If the following call panics, it indicates UnimplementedWordleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WordleService_ServiceDesc, srv)
}

func _WordleService_GetDailyWordleState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyWordleStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordleServiceServer).GetDailyWordleState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WordleService_GetDailyWordleState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordleServiceServer).GetDailyWordleState(ctx, req.(*GetDailyWordleStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WordleService_MakeWordleGuess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeWordleGuessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordleServiceServer).MakeWordleGuess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WordleService_MakeWordleGuess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordleServiceServer).MakeWordleGuess(ctx, req.(*MakeWordleGuessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WordleService_ServiceDesc is the grpc.ServiceDesc for WordleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WordleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.WordleService",
	HandlerType: (*WordleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDailyWordleState",
			Handler:    _WordleService_GetDailyWordleState_Handler,
		},
		{
			MethodName: "MakeWordleGuess",
			Handler:    _WordleService_MakeWordleGuess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/game.proto",
}
