// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../shared/templates/tracing.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package usecase

//go:generate gowrap gen -p github.com/go-park-mail-ru/2026_1_NaNcats/services/user/internal/usecase -i ClientProfileUseCase -t ../../../../shared/templates/tracing.tmpl -o client_profile_tracing_mw.go -v TracerName=user-service -l ""

import (
	"context"

	"github.com/go-park-mail-ru/2026_1_NaNcats/services/user/internal/domain"
	"go.opentelemetry.io/otel"
	otelcodes "go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

// ClientProfileUseCaseTracingMiddleware реализует интерфейс ClientProfileUseCase с поддержкой трассировки OpenTelemetry
type ClientProfileUseCaseTracingMiddleware struct {
	next   ClientProfileUseCase
	tracer trace.Tracer
}

// NewClientProfileUseCaseTracingMiddleware создает новый экземпляр декоратора для трассировки
func NewClientProfileUseCaseTracingMiddleware(next ClientProfileUseCase) ClientProfileUseCaseTracingMiddleware {
	return ClientProfileUseCaseTracingMiddleware{
		next:   next,
		tracer: otel.Tracer("user-service"),
	}
}

// ActivateStreakFreeze трассирует выполнение метода ActivateStreakFreeze
func (m ClientProfileUseCaseTracingMiddleware) ActivateStreakFreeze(ctx context.Context, accountID int64) (err error) {

	ctx, span := m.tracer.Start(ctx, "ClientProfileUseCase.ActivateStreakFreeze")

	defer span.End()

	err = m.next.ActivateStreakFreeze(ctx, accountID)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// CreateProfile трассирует выполнение метода CreateProfile
func (m ClientProfileUseCaseTracingMiddleware) CreateProfile(ctx context.Context, accountID int64, idempotencyKey string) (err error) {

	ctx, span := m.tracer.Start(ctx, "ClientProfileUseCase.CreateProfile")

	defer span.End()

	err = m.next.CreateProfile(ctx, accountID, idempotencyKey)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// GetByAccountID трассирует выполнение метода GetByAccountID
func (m ClientProfileUseCaseTracingMiddleware) GetByAccountID(ctx context.Context, accountID int64) (c2 domain.ClientProfile, err error) {

	ctx, span := m.tracer.Start(ctx, "ClientProfileUseCase.GetByAccountID")

	defer span.End()

	c2, err = m.next.GetByAccountID(ctx, accountID)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}

// IncrementStreak трассирует выполнение метода IncrementStreak
func (m ClientProfileUseCaseTracingMiddleware) IncrementStreak(ctx context.Context, accountID int64) (err error) {

	ctx, span := m.tracer.Start(ctx, "ClientProfileUseCase.IncrementStreak")

	defer span.End()

	err = m.next.IncrementStreak(ctx, accountID)

	if err != nil {
		span.RecordError(err)
		span.SetStatus(otelcodes.Error, err.Error())
	}

	return
}
