// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_NaNcats/services/order/internal/usecase (interfaces: OrderUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/order_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_NaNcats/services/order/internal/usecase OrderUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_NaNcats/services/order/internal/domain"
	events "github.com/go-park-mail-ru/2026_1_NaNcats/shared/pkg/rabbitmq/events"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderUseCase is a mock of OrderUseCase interface.
type MockOrderUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockOrderUseCaseMockRecorder
	isgomock struct{}
}

// MockOrderUseCaseMockRecorder is the mock recorder for MockOrderUseCase.
type MockOrderUseCaseMockRecorder struct {
	mock *MockOrderUseCase
}

// NewMockOrderUseCase creates a new mock instance.
func NewMockOrderUseCase(ctrl *gomock.Controller) *MockOrderUseCase {
	mock := &MockOrderUseCase{ctrl: ctrl}
	mock.recorder = &MockOrderUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderUseCase) EXPECT() *MockOrderUseCaseMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderUseCase) CreateOrder(ctx context.Context, req domain.CreateOrderInput, idempotencyKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, req, idempotencyKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderUseCaseMockRecorder) CreateOrder(ctx, req, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderUseCase)(nil).CreateOrder), ctx, req, idempotencyKey)
}

// GetOrders mocks base method.
func (m *MockOrderUseCase) GetOrders(ctx context.Context, userID int64) ([]domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, userID)
	ret0, _ := ret[0].([]domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockOrderUseCaseMockRecorder) GetOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockOrderUseCase)(nil).GetOrders), ctx, userID)
}

// PayForFriend mocks base method.
func (m *MockOrderUseCase) PayForFriend(ctx context.Context, splitID string, adminID int64, paymentMethodID, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PayForFriend", ctx, splitID, adminID, paymentMethodID, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// PayForFriend indicates an expected call of PayForFriend.
func (mr *MockOrderUseCaseMockRecorder) PayForFriend(ctx, splitID, adminID, paymentMethodID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PayForFriend", reflect.TypeOf((*MockOrderUseCase)(nil).PayForFriend), ctx, splitID, adminID, paymentMethodID, idempotencyKey)
}

// ProcessSagaReply mocks base method.
func (m *MockOrderUseCase) ProcessSagaReply(ctx context.Context, reply events.SagaReply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessSagaReply", ctx, reply)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessSagaReply indicates an expected call of ProcessSagaReply.
func (mr *MockOrderUseCaseMockRecorder) ProcessSagaReply(ctx, reply any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessSagaReply", reflect.TypeOf((*MockOrderUseCase)(nil).ProcessSagaReply), ctx, reply)
}

// UpdateOrderStatusByPaymentID mocks base method.
func (m *MockOrderUseCase) UpdateOrderStatusByPaymentID(ctx context.Context, paymentID, status, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatusByPaymentID", ctx, paymentID, status, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatusByPaymentID indicates an expected call of UpdateOrderStatusByPaymentID.
func (mr *MockOrderUseCaseMockRecorder) UpdateOrderStatusByPaymentID(ctx, paymentID, status, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatusByPaymentID", reflect.TypeOf((*MockOrderUseCase)(nil).UpdateOrderStatusByPaymentID), ctx, paymentID, status, idempotencyKey)
}
