// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package payment

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson377dcee4DecodeGithubComGoParkMailRu20261NaNcatsInternalDeliveryHandlerPayment(in *jlexer.Lexer, out *PaymentMethodResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "card_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CardType = string(in.String())
			}
		case "last4":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Last4 = string(in.String())
			}
		case "issuer_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IssuerName = string(in.String())
			}
		case "is_default":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsDefault = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson377dcee4EncodeGithubComGoParkMailRu20261NaNcatsInternalDeliveryHandlerPayment(out *jwriter.Writer, in PaymentMethodResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"card_type\":"
		out.RawString(prefix)
		out.String(string(in.CardType))
	}
	{
		const prefix string = ",\"last4\":"
		out.RawString(prefix)
		out.String(string(in.Last4))
	}
	if in.IssuerName != "" {
		const prefix string = ",\"issuer_name\":"
		out.RawString(prefix)
		out.String(string(in.IssuerName))
	}
	{
		const prefix string = ",\"is_default\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsDefault))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PaymentMethodResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson377dcee4EncodeGithubComGoParkMailRu20261NaNcatsInternalDeliveryHandlerPayment(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PaymentMethodResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson377dcee4EncodeGithubComGoParkMailRu20261NaNcatsInternalDeliveryHandlerPayment(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PaymentMethodResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson377dcee4DecodeGithubComGoParkMailRu20261NaNcatsInternalDeliveryHandlerPayment(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PaymentMethodResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson377dcee4DecodeGithubComGoParkMailRu20261NaNcatsInternalDeliveryHandlerPayment(l, v)
}
func easyjson377dcee4DecodeGithubComGoParkMailRu20261NaNcatsInternalDeliveryHandlerPayment1(in *jlexer.Lexer, out *BindingResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "confirmation_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfirmationURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson377dcee4EncodeGithubComGoParkMailRu20261NaNcatsInternalDeliveryHandlerPayment1(out *jwriter.Writer, in BindingResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"confirmation_url\":"
		out.RawString(prefix[1:])
		out.String(string(in.ConfirmationURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BindingResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson377dcee4EncodeGithubComGoParkMailRu20261NaNcatsInternalDeliveryHandlerPayment1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BindingResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson377dcee4EncodeGithubComGoParkMailRu20261NaNcatsInternalDeliveryHandlerPayment1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BindingResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson377dcee4DecodeGithubComGoParkMailRu20261NaNcatsInternalDeliveryHandlerPayment1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BindingResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson377dcee4DecodeGithubComGoParkMailRu20261NaNcatsInternalDeliveryHandlerPayment1(l, v)
}
