logger:
  level: "debug"

postgres:
  url: "postgres://user:password@localhost:5438/support_db?sslmode=disable"

grpc:
  port: "50058"
  timeout: "5s"

s3:
  bucket_name: "nancats-bucket"
  region: "ru-central1"

otel:
  service_name: "support-service"
