// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package promo

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson47107b8bDecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo(in *jlexer.Lexer, out *ValidatePromoResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "valid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Valid = bool(in.Bool())
			}
		case "discount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Discount = int64(in.Int64())
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reason = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson47107b8bEncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo(out *jwriter.Writer, in ValidatePromoResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"valid\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Valid))
	}
	{
		const prefix string = ",\"discount\":"
		out.RawString(prefix)
		out.Int64(int64(in.Discount))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ValidatePromoResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson47107b8bEncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ValidatePromoResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson47107b8bEncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ValidatePromoResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson47107b8bDecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ValidatePromoResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson47107b8bDecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo(l, v)
}
func easyjson47107b8bDecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo1(in *jlexer.Lexer, out *ValidatePromoRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "restaurant_brand_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RestaurantBrandID = int64(in.Int64())
			}
		case "order_amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OrderAmount = int64(in.Int64())
			}
		case "delivery_cost":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DeliveryCost = int64(in.Int64())
			}
		case "service_fee":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ServiceFee = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson47107b8bEncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo1(out *jwriter.Writer, in ValidatePromoRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"restaurant_brand_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.RestaurantBrandID))
	}
	{
		const prefix string = ",\"order_amount\":"
		out.RawString(prefix)
		out.Int64(int64(in.OrderAmount))
	}
	{
		const prefix string = ",\"delivery_cost\":"
		out.RawString(prefix)
		out.Int64(int64(in.DeliveryCost))
	}
	{
		const prefix string = ",\"service_fee\":"
		out.RawString(prefix)
		out.Int64(int64(in.ServiceFee))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ValidatePromoRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson47107b8bEncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ValidatePromoRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson47107b8bEncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ValidatePromoRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson47107b8bDecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ValidatePromoRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson47107b8bDecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo1(l, v)
}
func easyjson47107b8bDecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo2(in *jlexer.Lexer, out *UsePromoRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "order_public_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OrderPublicID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson47107b8bEncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo2(out *jwriter.Writer, in UsePromoRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"order_public_id\":"
		out.RawString(prefix)
		out.String(string(in.OrderPublicID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UsePromoRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson47107b8bEncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UsePromoRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson47107b8bEncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UsePromoRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson47107b8bDecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UsePromoRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson47107b8bDecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo2(l, v)
}
func easyjson47107b8bDecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo3(in *jlexer.Lexer, out *PromoCodeDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "discount_percent":
			if in.IsNull() {
				in.Skip()
				out.DiscountPercent = nil
			} else {
				if out.DiscountPercent == nil {
					out.DiscountPercent = new(int32)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.DiscountPercent = int32(in.Int32())
				}
			}
		case "discount_amount":
			if in.IsNull() {
				in.Skip()
				out.DiscountAmount = nil
			} else {
				if out.DiscountAmount == nil {
					out.DiscountAmount = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.DiscountAmount = int64(in.Int64())
				}
			}
		case "min_order_amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinOrderAmount = int64(in.Int64())
			}
		case "expires_at":
			if in.IsNull() {
				in.Skip()
				out.ExpiresAt = nil
			} else {
				if out.ExpiresAt == nil {
					out.ExpiresAt = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ExpiresAt = string(in.String())
				}
			}
		case "restaurant_brand_ids":
			if in.IsNull() {
				in.Skip()
				out.RestaurantBrandIDs = nil
			} else {
				in.Delim('[')
				if out.RestaurantBrandIDs == nil {
					if !in.IsDelim(']') {
						out.RestaurantBrandIDs = make([]int64, 0, 8)
					} else {
						out.RestaurantBrandIDs = []int64{}
					}
				} else {
					out.RestaurantBrandIDs = (out.RestaurantBrandIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = int64(in.Int64())
					}
					out.RestaurantBrandIDs = append(out.RestaurantBrandIDs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson47107b8bEncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo3(out *jwriter.Writer, in PromoCodeDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"discount_percent\":"
		out.RawString(prefix)
		if in.DiscountPercent == nil {
			out.RawString("null")
		} else {
			out.Int32(int32(*in.DiscountPercent))
		}
	}
	{
		const prefix string = ",\"discount_amount\":"
		out.RawString(prefix)
		if in.DiscountAmount == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.DiscountAmount))
		}
	}
	{
		const prefix string = ",\"min_order_amount\":"
		out.RawString(prefix)
		out.Int64(int64(in.MinOrderAmount))
	}
	{
		const prefix string = ",\"expires_at\":"
		out.RawString(prefix)
		if in.ExpiresAt == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.ExpiresAt))
		}
	}
	{
		const prefix string = ",\"restaurant_brand_ids\":"
		out.RawString(prefix)
		if in.RestaurantBrandIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.RestaurantBrandIDs {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PromoCodeDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson47107b8bEncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PromoCodeDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson47107b8bEncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PromoCodeDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson47107b8bDecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PromoCodeDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson47107b8bDecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo3(l, v)
}
func easyjson47107b8bDecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo4(in *jlexer.Lexer, out *BindPromoRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson47107b8bEncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo4(out *jwriter.Writer, in BindPromoRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.String(string(in.Code))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BindPromoRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson47107b8bEncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BindPromoRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson47107b8bEncodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BindPromoRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson47107b8bDecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BindPromoRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson47107b8bDecodeGithubComGoParkMailRu20261NaNcatsApiGatewayInternalDeliveryHttpPromo4(l, v)
}
