// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_NaNcats/api-gateway/internal/grpc_client/addressclient (interfaces: AddressClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/address_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_NaNcats/api-gateway/internal/grpc_client/addressclient AddressClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	addressclient "github.com/go-park-mail-ru/2026_1_NaNcats/api-gateway/internal/grpc_client/addressclient"
	gomock "go.uber.org/mock/gomock"
)

// MockAddressClient is a mock of AddressClient interface.
type MockAddressClient struct {
	ctrl     *gomock.Controller
	recorder *MockAddressClientMockRecorder
	isgomock struct{}
}

// MockAddressClientMockRecorder is the mock recorder for MockAddressClient.
type MockAddressClientMockRecorder struct {
	mock *MockAddressClient
}

// NewMockAddressClient creates a new mock instance.
func NewMockAddressClient(ctrl *gomock.Controller) *MockAddressClient {
	mock := &MockAddressClient{ctrl: ctrl}
	mock.recorder = &MockAddressClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddressClient) EXPECT() *MockAddressClientMockRecorder {
	return m.recorder
}

// AddAddress mocks base method.
func (m *MockAddressClient) AddAddress(ctx context.Context, userID int64, addr addressclient.Address, idempotencyKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAddress", ctx, userID, addr, idempotencyKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAddress indicates an expected call of AddAddress.
func (mr *MockAddressClientMockRecorder) AddAddress(ctx, userID, addr, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAddress", reflect.TypeOf((*MockAddressClient)(nil).AddAddress), ctx, userID, addr, idempotencyKey)
}

// CheckAddressExists mocks base method.
func (m *MockAddressClient) CheckAddressExists(ctx context.Context, userID int64, publicID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAddressExists", ctx, userID, publicID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAddressExists indicates an expected call of CheckAddressExists.
func (mr *MockAddressClientMockRecorder) CheckAddressExists(ctx, userID, publicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAddressExists", reflect.TypeOf((*MockAddressClient)(nil).CheckAddressExists), ctx, userID, publicID)
}

// DeleteAddress mocks base method.
func (m *MockAddressClient) DeleteAddress(ctx context.Context, userID int64, publicID, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddress", ctx, userID, publicID, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddress indicates an expected call of DeleteAddress.
func (mr *MockAddressClientMockRecorder) DeleteAddress(ctx, userID, publicID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddress", reflect.TypeOf((*MockAddressClient)(nil).DeleteAddress), ctx, userID, publicID, idempotencyKey)
}

// GetMyAddresses mocks base method.
func (m *MockAddressClient) GetMyAddresses(ctx context.Context, userID int64) ([]addressclient.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyAddresses", ctx, userID)
	ret0, _ := ret[0].([]addressclient.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyAddresses indicates an expected call of GetMyAddresses.
func (mr *MockAddressClientMockRecorder) GetMyAddresses(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyAddresses", reflect.TypeOf((*MockAddressClient)(nil).GetMyAddresses), ctx, userID)
}

// UpdateAddress mocks base method.
func (m *MockAddressClient) UpdateAddress(ctx context.Context, userID int64, addr addressclient.Address, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", ctx, userID, addr, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockAddressClientMockRecorder) UpdateAddress(ctx, userID, addr, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockAddressClient)(nil).UpdateAddress), ctx, userID, addr, idempotencyKey)
}
