// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_NaNcats/services/payment/internal/usecase (interfaces: PaymentUseCase,OrderClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/payment_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_NaNcats/services/payment/internal/usecase PaymentUseCase,OrderClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_NaNcats/services/payment/internal/domain"
	yookassa "github.com/go-park-mail-ru/2026_1_NaNcats/shared/pkg/api_clients/yookassa"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentUseCase is a mock of PaymentUseCase interface.
type MockPaymentUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentUseCaseMockRecorder
	isgomock struct{}
}

// MockPaymentUseCaseMockRecorder is the mock recorder for MockPaymentUseCase.
type MockPaymentUseCaseMockRecorder struct {
	mock *MockPaymentUseCase
}

// NewMockPaymentUseCase creates a new mock instance.
func NewMockPaymentUseCase(ctrl *gomock.Controller) *MockPaymentUseCase {
	mock := &MockPaymentUseCase{ctrl: ctrl}
	mock.recorder = &MockPaymentUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentUseCase) EXPECT() *MockPaymentUseCaseMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPaymentUseCase) CreatePayment(ctx context.Context, amount int64, paymentMethodID, idempotencyKey string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, amount, paymentMethodID, idempotencyKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentUseCaseMockRecorder) CreatePayment(ctx, amount, paymentMethodID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentUseCase)(nil).CreatePayment), ctx, amount, paymentMethodID, idempotencyKey)
}

// DeleteCard mocks base method.
func (m *MockPaymentUseCase) DeleteCard(ctx context.Context, cardID string, userID int64, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCard", ctx, cardID, userID, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCard indicates an expected call of DeleteCard.
func (mr *MockPaymentUseCaseMockRecorder) DeleteCard(ctx, cardID, userID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCard", reflect.TypeOf((*MockPaymentUseCase)(nil).DeleteCard), ctx, cardID, userID, idempotencyKey)
}

// GetUserCards mocks base method.
func (m *MockPaymentUseCase) GetUserCards(ctx context.Context, userID int64) ([]domain.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCards", ctx, userID)
	ret0, _ := ret[0].([]domain.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCards indicates an expected call of GetUserCards.
func (mr *MockPaymentUseCaseMockRecorder) GetUserCards(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCards", reflect.TypeOf((*MockPaymentUseCase)(nil).GetUserCards), ctx, userID)
}

// InitiateCardBinding mocks base method.
func (m *MockPaymentUseCase) InitiateCardBinding(ctx context.Context, userID int64, idempotencyKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateCardBinding", ctx, userID, idempotencyKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateCardBinding indicates an expected call of InitiateCardBinding.
func (mr *MockPaymentUseCaseMockRecorder) InitiateCardBinding(ctx, userID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateCardBinding", reflect.TypeOf((*MockPaymentUseCase)(nil).InitiateCardBinding), ctx, userID, idempotencyKey)
}

// ProcessPaymentMethodWebhook mocks base method.
func (m *MockPaymentUseCase) ProcessPaymentMethodWebhook(ctx context.Context, paymentMethod *yookassa.WebhookPaymentMethodObject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPaymentMethodWebhook", ctx, paymentMethod)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessPaymentMethodWebhook indicates an expected call of ProcessPaymentMethodWebhook.
func (mr *MockPaymentUseCaseMockRecorder) ProcessPaymentMethodWebhook(ctx, paymentMethod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPaymentMethodWebhook", reflect.TypeOf((*MockPaymentUseCase)(nil).ProcessPaymentMethodWebhook), ctx, paymentMethod)
}

// ProcessPaymentWebhook mocks base method.
func (m *MockPaymentUseCase) ProcessPaymentWebhook(ctx context.Context, payment *yookassa.WebhookPaymentObject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPaymentWebhook", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessPaymentWebhook indicates an expected call of ProcessPaymentWebhook.
func (mr *MockPaymentUseCaseMockRecorder) ProcessPaymentWebhook(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPaymentWebhook", reflect.TypeOf((*MockPaymentUseCase)(nil).ProcessPaymentWebhook), ctx, payment)
}

// RefreshPaymentStatus mocks base method.
func (m *MockPaymentUseCase) RefreshPaymentStatus(ctx context.Context, paymentID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshPaymentStatus", ctx, paymentID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshPaymentStatus indicates an expected call of RefreshPaymentStatus.
func (mr *MockPaymentUseCaseMockRecorder) RefreshPaymentStatus(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshPaymentStatus", reflect.TypeOf((*MockPaymentUseCase)(nil).RefreshPaymentStatus), ctx, paymentID)
}

// SetDefaultCard mocks base method.
func (m *MockPaymentUseCase) SetDefaultCard(ctx context.Context, cardID string, userID int64, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultCard", ctx, cardID, userID, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefaultCard indicates an expected call of SetDefaultCard.
func (mr *MockPaymentUseCaseMockRecorder) SetDefaultCard(ctx, cardID, userID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultCard", reflect.TypeOf((*MockPaymentUseCase)(nil).SetDefaultCard), ctx, cardID, userID, idempotencyKey)
}

// MockOrderClient is a mock of OrderClient interface.
type MockOrderClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrderClientMockRecorder
	isgomock struct{}
}

// MockOrderClientMockRecorder is the mock recorder for MockOrderClient.
type MockOrderClientMockRecorder struct {
	mock *MockOrderClient
}

// NewMockOrderClient creates a new mock instance.
func NewMockOrderClient(ctrl *gomock.Controller) *MockOrderClient {
	mock := &MockOrderClient{ctrl: ctrl}
	mock.recorder = &MockOrderClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderClient) EXPECT() *MockOrderClientMockRecorder {
	return m.recorder
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderClient) UpdateOrderStatus(ctx context.Context, paymentID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, paymentID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderClientMockRecorder) UpdateOrderStatus(ctx, paymentID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderClient)(nil).UpdateOrderStatus), ctx, paymentID, status)
}
