DROP TABLE IF EXISTS "idempotency_records" CASCADE;
DROP TABLE IF EXISTS "outbox_events" CASCADE;
DROP TABLE IF EXISTS "cart_invite" CASCADE;
DROP TABLE IF EXISTS "cart_member" CASCADE;
DROP TABLE IF EXISTS "cart_dish" CASCADE;
DROP TABLE IF EXISTS "cart" CASCADE;

DROP TYPE IF EXISTS cart_status CASCADE;
DROP TYPE IF EXISTS cart_mode CASCADE;
