serviceName: auth-service
image:
  repository: ghcr.io/go-park-mail-ru/2026_1_nancats/auth
service:
  port: 50054
env:
  CONFIG_PATH: "./services/auth/config.yaml"
  REDIS_URL: "redis://redis-service-redis:6379/0"
  USER_SERVICE_ADDR: "user-service:50052"
