serviceName: payment-service
image:
  repository: ghcr.io/go-park-mail-ru/2026_1_nancats/payment
service:
  port: 50056
env:
  CONFIG_PATH: "./services/payment/config.yaml"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672/"
  REDIS_URL: "redis://redis-service-master:6379/0"
  ORDER_SERVICE_ADDR: "order-service:50057"
  YOOKASSA_SHOP_ID: "1325612"
  YOOKASSA_RETURN_URL: "https://foodcourt.fun/profile"
  DATABASE_URL: "postgres://db_user:$(DB_PASSWORD)@postgres-service-postgresql:5432/payment_db?sslmode=disable"
secrets:
  DB_PASSWORD:
    secretName: nancats-prod-secrets
    secretKey: db-password
  YOOKASSA_SECRET_KEY:
    secretName: nancats-prod-secrets
    secretKey: yookassa-secret-key
  