serviceName: restaurant-service
image:
  repository: ghcr.io/go-park-mail-ru/2026_1_nancats/restaurant
service:
  port: 50053
env:
  CONFIG_PATH: "./services/restaurant/config.yaml"
  DATABASE_URL: "postgres://nancat_admin:$(DB_PASSWORD)@postgres-service-postgresql:5432/restaurant_db?sslmode=disable"
  ORDER_SERVICE_ADDR: "order-service:50057"
secrets:
  DB_PASSWORD:
    secretName: nancats-prod-secrets
    secretKey: db-password
