basePath: /api
definitions:
  handler.LoginRequest:
    properties:
      login:
        description: Email пользователя
        example: user@mail.ru
        type: string
      password:
        description: Пароль в открытом виде
        example: qwerty12345
        type: string
    type: object
  handler.LoginResponse:
    properties:
      id:
        description: Уникальный ID пользователя в системе
        example: 1
        type: integer
      name:
        description: Имя для отображения в интерфейсе
        example: Иван
        type: string
    type: object
  handler.RegisterRequest:
    properties:
      email:
        description: Email пользователя
        example: user@mail.ru
        type: string
      name:
        description: Имя пользователя
        example: Иван
        type: string
      password:
        description: Пароль в открытом виде
        example: qwerty12345
        type: string
    type: object
  handler.RegisterResponse:
    properties:
      created_at:
        description: Время создания аккаунта по стандарту RFC 3339
        example: 2006-01-02T15:04:05Z07:00
        type: string
      email:
        description: Email пользователя
        example: user@mail.ru
        type: string
      id:
        description: Уникальный ID пользователя в системе
        example: 1
        type: integer
      name:
        description: Имя для отображения в интерфейсе
        example: Иван
        type: string
    type: object
  response.ErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: Неверный формат запроса
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API бэкенда для проекта "Delivery Club" от команды NaNcats
  title: NaNcats Delivery API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Проверяет учетные данные (логин и пароль) и создает сессионную
        куку
      parameters:
      - description: Данные для входа
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный вход и создание сессии
          schema:
            $ref: '#/definitions/handler.LoginResponse'
        "400":
          description: Неверный формат JSON
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Авторизация пользователя
      tags:
      - auth
  /logout:
    post:
      consumes:
      - application/json
      description: Удаляет информацию о текущей сессии и принудительно протухает куку
        с сессией
      produces:
      - application/json
      responses:
        "200":
          description: Успешный выход
        "401":
          description: Сессия не найдена
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Сессия не найдена в базе данных
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Выход из текущей
      tags:
      - auth
  /me:
    get:
      consumes:
      - application/json
      description: Возвращает данные профиля пользователя, если сессионная кука валидна
      produces:
      - application/json
      responses:
        "200":
          description: Успешный вход и создание сессии
          schema:
            $ref: '#/definitions/handler.LoginResponse'
        "401":
          description: Сессия не найдена
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Проверка текущей сессии
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Проверяет, существует ли пользователь с указанными данными или
        нет, регистрирует его и создает сессионную куку
      parameters:
      - description: Данные для регистрации
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Успешная регистрация и создание сессии
          schema:
            $ref: '#/definitions/handler.RegisterResponse'
        "400":
          description: Неверный формат JSON
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Регистрация пользователя
      tags:
      - auth
swagger: "2.0"
