// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: payment/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefreshPaymentStatusRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	YookassaPaymentId string                 `protobuf:"bytes,1,opt,name=yookassa_payment_id,json=yookassaPaymentId,proto3" json:"yookassa_payment_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RefreshPaymentStatusRequest) Reset() {
	*x = RefreshPaymentStatusRequest{}
	mi := &file_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshPaymentStatusRequest) ProtoMessage() {}

func (x *RefreshPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*RefreshPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *RefreshPaymentStatusRequest) GetYookassaPaymentId() string {
	if x != nil {
		return x.YookassaPaymentId
	}
	return ""
}

type RefreshPaymentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshPaymentStatusResponse) Reset() {
	*x = RefreshPaymentStatusResponse{}
	mi := &file_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshPaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshPaymentStatusResponse) ProtoMessage() {}

func (x *RefreshPaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshPaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*RefreshPaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshPaymentStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PaymentMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExternalId    string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	First6        string                 `protobuf:"bytes,4,opt,name=first6,proto3" json:"first6,omitempty"`
	Last4         string                 `protobuf:"bytes,5,opt,name=last4,proto3" json:"last4,omitempty"`
	ExpiryMonth   string                 `protobuf:"bytes,6,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month,omitempty"`
	ExpiryYear    string                 `protobuf:"bytes,7,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year,omitempty"`
	CardType      string                 `protobuf:"bytes,8,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	IssuerName    string                 `protobuf:"bytes,9,opt,name=issuer_name,json=issuerName,proto3" json:"issuer_name,omitempty"`
	IsDefault     bool                   `protobuf:"varint,10,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMethod) Reset() {
	*x = PaymentMethod{}
	mi := &file_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethod) ProtoMessage() {}

func (x *PaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethod.ProtoReflect.Descriptor instead.
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentMethod) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentMethod) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PaymentMethod) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *PaymentMethod) GetFirst6() string {
	if x != nil {
		return x.First6
	}
	return ""
}

func (x *PaymentMethod) GetLast4() string {
	if x != nil {
		return x.Last4
	}
	return ""
}

func (x *PaymentMethod) GetExpiryMonth() string {
	if x != nil {
		return x.ExpiryMonth
	}
	return ""
}

func (x *PaymentMethod) GetExpiryYear() string {
	if x != nil {
		return x.ExpiryYear
	}
	return ""
}

func (x *PaymentMethod) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *PaymentMethod) GetIssuerName() string {
	if x != nil {
		return x.IssuerName
	}
	return ""
}

func (x *PaymentMethod) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type CardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	First6        string                 `protobuf:"bytes,1,opt,name=first6,proto3" json:"first6,omitempty"`
	Last4         string                 `protobuf:"bytes,2,opt,name=last4,proto3" json:"last4,omitempty"`
	ExpiryMonth   string                 `protobuf:"bytes,3,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month,omitempty"`
	ExpiryYear    string                 `protobuf:"bytes,4,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year,omitempty"`
	CardType      string                 `protobuf:"bytes,5,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	IssuerName    string                 `protobuf:"bytes,6,opt,name=issuer_name,json=issuerName,proto3" json:"issuer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardInfo) Reset() {
	*x = CardInfo{}
	mi := &file_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardInfo) ProtoMessage() {}

func (x *CardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardInfo.ProtoReflect.Descriptor instead.
func (*CardInfo) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CardInfo) GetFirst6() string {
	if x != nil {
		return x.First6
	}
	return ""
}

func (x *CardInfo) GetLast4() string {
	if x != nil {
		return x.Last4
	}
	return ""
}

func (x *CardInfo) GetExpiryMonth() string {
	if x != nil {
		return x.ExpiryMonth
	}
	return ""
}

func (x *CardInfo) GetExpiryYear() string {
	if x != nil {
		return x.ExpiryYear
	}
	return ""
}

func (x *CardInfo) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CardInfo) GetIssuerName() string {
	if x != nil {
		return x.IssuerName
	}
	return ""
}

type CreatePaymentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Amount          int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethodId string                 `protobuf:"bytes,2,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *CreatePaymentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreatePaymentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentId       string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	ConfirmationUrl string                 `protobuf:"bytes,2,opt,name=confirmation_url,json=confirmationUrl,proto3" json:"confirmation_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_payment_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreatePaymentResponse) GetConfirmationUrl() string {
	if x != nil {
		return x.ConfirmationUrl
	}
	return ""
}

type InitiateCardBindingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitiateCardBindingRequest) Reset() {
	*x = InitiateCardBindingRequest{}
	mi := &file_payment_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCardBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCardBindingRequest) ProtoMessage() {}

func (x *InitiateCardBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCardBindingRequest.ProtoReflect.Descriptor instead.
func (*InitiateCardBindingRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{6}
}

func (x *InitiateCardBindingRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InitiateCardBindingRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type InitiateCardBindingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfirmationUrl string                 `protobuf:"bytes,1,opt,name=confirmation_url,json=confirmationUrl,proto3" json:"confirmation_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitiateCardBindingResponse) Reset() {
	*x = InitiateCardBindingResponse{}
	mi := &file_payment_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCardBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCardBindingResponse) ProtoMessage() {}

func (x *InitiateCardBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCardBindingResponse.ProtoReflect.Descriptor instead.
func (*InitiateCardBindingResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{7}
}

func (x *InitiateCardBindingResponse) GetConfirmationUrl() string {
	if x != nil {
		return x.ConfirmationUrl
	}
	return ""
}

type GetUserCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCardsRequest) Reset() {
	*x = GetUserCardsRequest{}
	mi := &file_payment_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCardsRequest) ProtoMessage() {}

func (x *GetUserCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCardsRequest.ProtoReflect.Descriptor instead.
func (*GetUserCardsRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserCardsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cards         []*PaymentMethod       `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCardsResponse) Reset() {
	*x = GetUserCardsResponse{}
	mi := &file_payment_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCardsResponse) ProtoMessage() {}

func (x *GetUserCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCardsResponse.ProtoReflect.Descriptor instead.
func (*GetUserCardsResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserCardsResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserCardsResponse) GetCards() []*PaymentMethod {
	if x != nil {
		return x.Cards
	}
	return nil
}

type ChangeCardRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardId         string                 `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChangeCardRequest) Reset() {
	*x = ChangeCardRequest{}
	mi := &file_payment_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeCardRequest) ProtoMessage() {}

func (x *ChangeCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeCardRequest.ProtoReflect.Descriptor instead.
func (*ChangeCardRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeCardRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChangeCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *ChangeCardRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ProcessPaymentMethodWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Saved         bool                   `protobuf:"varint,3,opt,name=saved,proto3" json:"saved,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Card          *CardInfo              `protobuf:"bytes,5,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentMethodWebhookRequest) Reset() {
	*x = ProcessPaymentMethodWebhookRequest{}
	mi := &file_payment_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentMethodWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentMethodWebhookRequest) ProtoMessage() {}

func (x *ProcessPaymentMethodWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentMethodWebhookRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentMethodWebhookRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{11}
}

func (x *ProcessPaymentMethodWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessPaymentMethodWebhookRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessPaymentMethodWebhookRequest) GetSaved() bool {
	if x != nil {
		return x.Saved
	}
	return false
}

func (x *ProcessPaymentMethodWebhookRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProcessPaymentMethodWebhookRequest) GetCard() *CardInfo {
	if x != nil {
		return x.Card
	}
	return nil
}

type ProcessPaymentWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentWebhookRequest) Reset() {
	*x = ProcessPaymentWebhookRequest{}
	mi := &file_payment_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentWebhookRequest) ProtoMessage() {}

func (x *ProcessPaymentWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentWebhookRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentWebhookRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{12}
}

func (x *ProcessPaymentWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessPaymentWebhookRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_payment_payment_proto protoreflect.FileDescriptor

const file_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x15payment/payment.proto\x12\apayment\x1a\x1bgoogle/protobuf/empty.proto\"M\n" +
	"\x1bRefreshPaymentStatusRequest\x12.\n" +
	"\x13yookassa_payment_id\x18\x01 \x01(\tR\x11yookassaPaymentId\"6\n" +
	"\x1cRefreshPaymentStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xa8\x02\n" +
	"\rPaymentMethod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\x12\x16\n" +
	"\x06first6\x18\x04 \x01(\tR\x06first6\x12\x14\n" +
	"\x05last4\x18\x05 \x01(\tR\x05last4\x12!\n" +
	"\fexpiry_month\x18\x06 \x01(\tR\vexpiryMonth\x12\x1f\n" +
	"\vexpiry_year\x18\a \x01(\tR\n" +
	"expiryYear\x12\x1b\n" +
	"\tcard_type\x18\b \x01(\tR\bcardType\x12\x1f\n" +
	"\vissuer_name\x18\t \x01(\tR\n" +
	"issuerName\x12\x1d\n" +
	"\n" +
	"is_default\x18\n" +
	" \x01(\bR\tisDefault\"\xba\x01\n" +
	"\bCardInfo\x12\x16\n" +
	"\x06first6\x18\x01 \x01(\tR\x06first6\x12\x14\n" +
	"\x05last4\x18\x02 \x01(\tR\x05last4\x12!\n" +
	"\fexpiry_month\x18\x03 \x01(\tR\vexpiryMonth\x12\x1f\n" +
	"\vexpiry_year\x18\x04 \x01(\tR\n" +
	"expiryYear\x12\x1b\n" +
	"\tcard_type\x18\x05 \x01(\tR\bcardType\x12\x1f\n" +
	"\vissuer_name\x18\x06 \x01(\tR\n" +
	"issuerName\"\x83\x01\n" +
	"\x14CreatePaymentRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12*\n" +
	"\x11payment_method_id\x18\x02 \x01(\tR\x0fpaymentMethodId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"a\n" +
	"\x15CreatePaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12)\n" +
	"\x10confirmation_url\x18\x02 \x01(\tR\x0fconfirmationUrl\"^\n" +
	"\x1aInitiateCardBindingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"H\n" +
	"\x1bInitiateCardBindingResponse\x12)\n" +
	"\x10confirmation_url\x18\x01 \x01(\tR\x0fconfirmationUrl\".\n" +
	"\x13GetUserCardsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"]\n" +
	"\x14GetUserCardsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12,\n" +
	"\x05cards\x18\x02 \x03(\v2\x16.payment.PaymentMethodR\x05cards\"n\n" +
	"\x11ChangeCardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"\x9d\x01\n" +
	"\"ProcessPaymentMethodWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05saved\x18\x03 \x01(\bR\x05saved\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12%\n" +
	"\x04card\x18\x05 \x01(\v2\x11.payment.CardInfoR\x04card\"F\n" +
	"\x1cProcessPaymentWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xb8\x05\n" +
	"\x0ePaymentService\x12N\n" +
	"\rCreatePayment\x12\x1d.payment.CreatePaymentRequest\x1a\x1e.payment.CreatePaymentResponse\x12`\n" +
	"\x13InitiateCardBinding\x12#.payment.InitiateCardBindingRequest\x1a$.payment.InitiateCardBindingResponse\x12K\n" +
	"\fGetUserCards\x12\x1c.payment.GetUserCardsRequest\x1a\x1d.payment.GetUserCardsResponse\x12D\n" +
	"\x0eSetDefaultCard\x12\x1a.payment.ChangeCardRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"DeleteCard\x12\x1a.payment.ChangeCardRequest\x1a\x16.google.protobuf.Empty\x12b\n" +
	"\x1bProcessPaymentMethodWebhook\x12+.payment.ProcessPaymentMethodWebhookRequest\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x15ProcessPaymentWebhook\x12%.payment.ProcessPaymentWebhookRequest\x1a\x16.google.protobuf.Empty\x12c\n" +
	"\x14RefreshPaymentStatus\x12$.payment.RefreshPaymentStatusRequest\x1a%.payment.RefreshPaymentStatusResponseB@Z>github.com/go-park-mail-ru/2026_1_NaNcats/shared/proto/paymentb\x06proto3"

var (
	file_payment_payment_proto_rawDescOnce sync.Once
	file_payment_payment_proto_rawDescData []byte
)

func file_payment_payment_proto_rawDescGZIP() []byte {
	file_payment_payment_proto_rawDescOnce.Do(func() {
		file_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_payment_proto_rawDesc), len(file_payment_payment_proto_rawDesc)))
	})
	return file_payment_payment_proto_rawDescData
}

var file_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_payment_payment_proto_goTypes = []any{
	(*RefreshPaymentStatusRequest)(nil),        // 0: payment.RefreshPaymentStatusRequest
	(*RefreshPaymentStatusResponse)(nil),       // 1: payment.RefreshPaymentStatusResponse
	(*PaymentMethod)(nil),                      // 2: payment.PaymentMethod
	(*CardInfo)(nil),                           // 3: payment.CardInfo
	(*CreatePaymentRequest)(nil),               // 4: payment.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),              // 5: payment.CreatePaymentResponse
	(*InitiateCardBindingRequest)(nil),         // 6: payment.InitiateCardBindingRequest
	(*InitiateCardBindingResponse)(nil),        // 7: payment.InitiateCardBindingResponse
	(*GetUserCardsRequest)(nil),                // 8: payment.GetUserCardsRequest
	(*GetUserCardsResponse)(nil),               // 9: payment.GetUserCardsResponse
	(*ChangeCardRequest)(nil),                  // 10: payment.ChangeCardRequest
	(*ProcessPaymentMethodWebhookRequest)(nil), // 11: payment.ProcessPaymentMethodWebhookRequest
	(*ProcessPaymentWebhookRequest)(nil),       // 12: payment.ProcessPaymentWebhookRequest
	(*emptypb.Empty)(nil),                      // 13: google.protobuf.Empty
}
var file_payment_payment_proto_depIdxs = []int32{
	2,  // 0: payment.GetUserCardsResponse.cards:type_name -> payment.PaymentMethod
	3,  // 1: payment.ProcessPaymentMethodWebhookRequest.card:type_name -> payment.CardInfo
	4,  // 2: payment.PaymentService.CreatePayment:input_type -> payment.CreatePaymentRequest
	6,  // 3: payment.PaymentService.InitiateCardBinding:input_type -> payment.InitiateCardBindingRequest
	8,  // 4: payment.PaymentService.GetUserCards:input_type -> payment.GetUserCardsRequest
	10, // 5: payment.PaymentService.SetDefaultCard:input_type -> payment.ChangeCardRequest
	10, // 6: payment.PaymentService.DeleteCard:input_type -> payment.ChangeCardRequest
	11, // 7: payment.PaymentService.ProcessPaymentMethodWebhook:input_type -> payment.ProcessPaymentMethodWebhookRequest
	12, // 8: payment.PaymentService.ProcessPaymentWebhook:input_type -> payment.ProcessPaymentWebhookRequest
	0,  // 9: payment.PaymentService.RefreshPaymentStatus:input_type -> payment.RefreshPaymentStatusRequest
	5,  // 10: payment.PaymentService.CreatePayment:output_type -> payment.CreatePaymentResponse
	7,  // 11: payment.PaymentService.InitiateCardBinding:output_type -> payment.InitiateCardBindingResponse
	9,  // 12: payment.PaymentService.GetUserCards:output_type -> payment.GetUserCardsResponse
	13, // 13: payment.PaymentService.SetDefaultCard:output_type -> google.protobuf.Empty
	13, // 14: payment.PaymentService.DeleteCard:output_type -> google.protobuf.Empty
	13, // 15: payment.PaymentService.ProcessPaymentMethodWebhook:output_type -> google.protobuf.Empty
	13, // 16: payment.PaymentService.ProcessPaymentWebhook:output_type -> google.protobuf.Empty
	1,  // 17: payment.PaymentService.RefreshPaymentStatus:output_type -> payment.RefreshPaymentStatusResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_payment_payment_proto_init() }
func file_payment_payment_proto_init() {
	if File_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_payment_proto_rawDesc), len(file_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_payment_proto_goTypes,
		DependencyIndexes: file_payment_payment_proto_depIdxs,
		MessageInfos:      file_payment_payment_proto_msgTypes,
	}.Build()
	File_payment_payment_proto = out.File
	file_payment_payment_proto_goTypes = nil
	file_payment_payment_proto_depIdxs = nil
}
