// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: payment/payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_CreatePayment_FullMethodName               = "/payment.PaymentService/CreatePayment"
	PaymentService_InitiateCardBinding_FullMethodName         = "/payment.PaymentService/InitiateCardBinding"
	PaymentService_GetUserCards_FullMethodName                = "/payment.PaymentService/GetUserCards"
	PaymentService_SetDefaultCard_FullMethodName              = "/payment.PaymentService/SetDefaultCard"
	PaymentService_DeleteCard_FullMethodName                  = "/payment.PaymentService/DeleteCard"
	PaymentService_ProcessPaymentMethodWebhook_FullMethodName = "/payment.PaymentService/ProcessPaymentMethodWebhook"
	PaymentService_ProcessPaymentWebhook_FullMethodName       = "/payment.PaymentService/ProcessPaymentWebhook"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Микросервис оплаты
type PaymentServiceClient interface {
	// Метод создания платежа
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
	// Метод привязки карты
	InitiateCardBinding(ctx context.Context, in *InitiateCardBindingRequest, opts ...grpc.CallOption) (*InitiateCardBindingResponse, error)
	// Метод получения карт пользователя
	GetUserCards(ctx context.Context, in *GetUserCardsRequest, opts ...grpc.CallOption) (*GetUserCardsResponse, error)
	// Метод установки дефолтной карты
	SetDefaultCard(ctx context.Context, in *ChangeCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Метод удаления карты
	DeleteCard(ctx context.Context, in *ChangeCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Вебхук для обработки привязки карты
	ProcessPaymentMethodWebhook(ctx context.Context, in *ProcessPaymentMethodWebhookRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Вебхук для создания платежа
	ProcessPaymentWebhook(ctx context.Context, in *ProcessPaymentWebhookRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentResponse)
	err := c.cc.Invoke(ctx, PaymentService_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) InitiateCardBinding(ctx context.Context, in *InitiateCardBindingRequest, opts ...grpc.CallOption) (*InitiateCardBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateCardBindingResponse)
	err := c.cc.Invoke(ctx, PaymentService_InitiateCardBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetUserCards(ctx context.Context, in *GetUserCardsRequest, opts ...grpc.CallOption) (*GetUserCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserCardsResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetUserCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) SetDefaultCard(ctx context.Context, in *ChangeCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaymentService_SetDefaultCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) DeleteCard(ctx context.Context, in *ChangeCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaymentService_DeleteCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ProcessPaymentMethodWebhook(ctx context.Context, in *ProcessPaymentMethodWebhookRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaymentService_ProcessPaymentMethodWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ProcessPaymentWebhook(ctx context.Context, in *ProcessPaymentWebhookRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaymentService_ProcessPaymentWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
//
// Микросервис оплаты
type PaymentServiceServer interface {
	// Метод создания платежа
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	// Метод привязки карты
	InitiateCardBinding(context.Context, *InitiateCardBindingRequest) (*InitiateCardBindingResponse, error)
	// Метод получения карт пользователя
	GetUserCards(context.Context, *GetUserCardsRequest) (*GetUserCardsResponse, error)
	// Метод установки дефолтной карты
	SetDefaultCard(context.Context, *ChangeCardRequest) (*emptypb.Empty, error)
	// Метод удаления карты
	DeleteCard(context.Context, *ChangeCardRequest) (*emptypb.Empty, error)
	// Вебхук для обработки привязки карты
	ProcessPaymentMethodWebhook(context.Context, *ProcessPaymentMethodWebhookRequest) (*emptypb.Empty, error)
	// Вебхук для создания платежа
	ProcessPaymentWebhook(context.Context, *ProcessPaymentWebhookRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPaymentServiceServer) InitiateCardBinding(context.Context, *InitiateCardBindingRequest) (*InitiateCardBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateCardBinding not implemented")
}
func (UnimplementedPaymentServiceServer) GetUserCards(context.Context, *GetUserCardsRequest) (*GetUserCardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserCards not implemented")
}
func (UnimplementedPaymentServiceServer) SetDefaultCard(context.Context, *ChangeCardRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDefaultCard not implemented")
}
func (UnimplementedPaymentServiceServer) DeleteCard(context.Context, *ChangeCardRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCard not implemented")
}
func (UnimplementedPaymentServiceServer) ProcessPaymentMethodWebhook(context.Context, *ProcessPaymentMethodWebhookRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessPaymentMethodWebhook not implemented")
}
func (UnimplementedPaymentServiceServer) ProcessPaymentWebhook(context.Context, *ProcessPaymentWebhookRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessPaymentWebhook not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_InitiateCardBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateCardBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).InitiateCardBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_InitiateCardBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).InitiateCardBinding(ctx, req.(*InitiateCardBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetUserCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetUserCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetUserCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetUserCards(ctx, req.(*GetUserCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_SetDefaultCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).SetDefaultCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_SetDefaultCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).SetDefaultCard(ctx, req.(*ChangeCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_DeleteCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).DeleteCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_DeleteCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).DeleteCard(ctx, req.(*ChangeCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ProcessPaymentMethodWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessPaymentMethodWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ProcessPaymentMethodWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ProcessPaymentMethodWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ProcessPaymentMethodWebhook(ctx, req.(*ProcessPaymentMethodWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ProcessPaymentWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessPaymentWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ProcessPaymentWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ProcessPaymentWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ProcessPaymentWebhook(ctx, req.(*ProcessPaymentWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayment",
			Handler:    _PaymentService_CreatePayment_Handler,
		},
		{
			MethodName: "InitiateCardBinding",
			Handler:    _PaymentService_InitiateCardBinding_Handler,
		},
		{
			MethodName: "GetUserCards",
			Handler:    _PaymentService_GetUserCards_Handler,
		},
		{
			MethodName: "SetDefaultCard",
			Handler:    _PaymentService_SetDefaultCard_Handler,
		},
		{
			MethodName: "DeleteCard",
			Handler:    _PaymentService_DeleteCard_Handler,
		},
		{
			MethodName: "ProcessPaymentMethodWebhook",
			Handler:    _PaymentService_ProcessPaymentMethodWebhook_Handler,
		},
		{
			MethodName: "ProcessPaymentWebhook",
			Handler:    _PaymentService_ProcessPaymentWebhook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/payment.proto",
}
