{
 "title": "NaNcats System & Services",
 "description": "System & Services",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Host RAM"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Host CPU"
    }
   ]
  },
  {
   "title": "Disk Free Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "Disk ({{mountpoint}})"
    }
   ]
  },
  { "title": "API Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Gateway Traffic (Requests per minute)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (http_request_method, http_route) (rate(nancats_http_server_request_duration_seconds_count[1m])) * 60",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "HTTP Latency (P99)",
   "type": "timeseries",
   "description": "99-й процентиль, время самого медленного из 100 запросов",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, http_route) (rate(nancats_http_server_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Server Errors (5xx) RPM",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (http_route, http_response_status_code) (rate(nancats_http_server_request_duration_seconds_count{http_response_status_code=~\"5..\"}[1m])) * 60",
     "legendFormat": "{{http_route}} - Status: {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Server & Client HTTP Errors",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (http_route, http_response_status_code) (rate(nancats_http_server_request_duration_seconds_count{http_response_status_code=~\"[45]..\"}[1m])) * 60",
     "legendFormat": "{{http_route}} - Status: {{http_response_status_code}}"
    }
   ]
  },
  { "title": "Internal Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "gRPC Hits per Service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (exported_job, rpc_method) (rate(nancats_rpc_server_call_duration_seconds_count[1m]))",
     "legendFormat": "{{rpc_method}}"
    }
   ]
  },
  {
   "title": "Services Latency (P99)",
   "type": "timeseries",
   "description": "99-й процентиль, время самого медленного из 100 запросов",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, exported_job, rpc_method) (rate(nancats_rpc_server_call_duration_seconds_bucket[5m])))",
     "legendFormat": "{{rpc_method}}"
    }
   ]
  },
  {
   "title": "Server & Client Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (exported_job, rpc_method, rpc_response_status_code) (\n  rate(nancats_rpc_server_call_duration_seconds_count{rpc_response_status_code!=\"OK\"}[1m])\n) * 60",
     "legendFormat": "{{rpc_method}}: {{rpc_response_status_code}}"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (exported_job, rpc_method, rpc_response_status_code) (\n  rate(nancats_rpc_server_call_duration_seconds_count{rpc_response_status_code=~\"INTERNAL|UNKNOWN|DATA_LOSS|DEADLINE_EXCEEDED|UNAVAILABLE\"}[1m])\n) * 60",
     "legendFormat": "{{rpc_method}}: {{rpc_response_status_code}}"
    }
   ]
  }
 ]
}