// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/repository (interfaces: ExtendedDishRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/extended_dish_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/repository ExtendedDishRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockExtendedDishRepository is a mock of ExtendedDishRepository interface.
type MockExtendedDishRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExtendedDishRepositoryMockRecorder
	isgomock struct{}
}

// MockExtendedDishRepositoryMockRecorder is the mock recorder for MockExtendedDishRepository.
type MockExtendedDishRepositoryMockRecorder struct {
	mock *MockExtendedDishRepository
}

// NewMockExtendedDishRepository creates a new mock instance.
func NewMockExtendedDishRepository(ctrl *gomock.Controller) *MockExtendedDishRepository {
	mock := &MockExtendedDishRepository{ctrl: ctrl}
	mock.recorder = &MockExtendedDishRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtendedDishRepository) EXPECT() *MockExtendedDishRepositoryMockRecorder {
	return m.recorder
}

// SearchDishes mocks base method.
func (m *MockExtendedDishRepository) SearchDishes(ctx context.Context, query string, limit int) ([]domain.Dish, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchDishes", ctx, query, limit)
	ret0, _ := ret[0].([]domain.Dish)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDishes indicates an expected call of SearchDishes.
func (mr *MockExtendedDishRepositoryMockRecorder) SearchDishes(ctx, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDishes", reflect.TypeOf((*MockExtendedDishRepository)(nil).SearchDishes), ctx, query, limit)
}

// SearchDishesByBrand mocks base method.
func (m *MockExtendedDishRepository) SearchDishesByBrand(ctx context.Context, brandID int64, query string, limit int) ([]domain.Dish, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchDishesByBrand", ctx, brandID, query, limit)
	ret0, _ := ret[0].([]domain.Dish)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDishesByBrand indicates an expected call of SearchDishesByBrand.
func (mr *MockExtendedDishRepositoryMockRecorder) SearchDishesByBrand(ctx, brandID, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDishesByBrand", reflect.TypeOf((*MockExtendedDishRepository)(nil).SearchDishesByBrand), ctx, brandID, query, limit)
}
