// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/repository (interfaces: RestaurantBrandRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/restaurant_brand_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/repository RestaurantBrandRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_NaNcats/services/restaurant/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRestaurantBrandRepository is a mock of RestaurantBrandRepository interface.
type MockRestaurantBrandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRestaurantBrandRepositoryMockRecorder
	isgomock struct{}
}

// MockRestaurantBrandRepositoryMockRecorder is the mock recorder for MockRestaurantBrandRepository.
type MockRestaurantBrandRepositoryMockRecorder struct {
	mock *MockRestaurantBrandRepository
}

// NewMockRestaurantBrandRepository creates a new mock instance.
func NewMockRestaurantBrandRepository(ctrl *gomock.Controller) *MockRestaurantBrandRepository {
	mock := &MockRestaurantBrandRepository{ctrl: ctrl}
	mock.recorder = &MockRestaurantBrandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestaurantBrandRepository) EXPECT() *MockRestaurantBrandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRestaurantBrandRepository) Create(ctx context.Context, b domain.RestaurantBrand, idempotencyKey string) (domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b, idempotencyKey)
	ret0, _ := ret[0].(domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRestaurantBrandRepositoryMockRecorder) Create(ctx, b, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRestaurantBrandRepository)(nil).Create), ctx, b, idempotencyKey)
}

// Delete mocks base method.
func (m *MockRestaurantBrandRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRestaurantBrandRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRestaurantBrandRepository)(nil).Delete), ctx, id)
}

// GetAllCategories mocks base method.
func (m *MockRestaurantBrandRepository) GetAllCategories(ctx context.Context) ([]domain.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCategories", ctx)
	ret0, _ := ret[0].([]domain.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCategories indicates an expected call of GetAllCategories.
func (mr *MockRestaurantBrandRepositoryMockRecorder) GetAllCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCategories", reflect.TypeOf((*MockRestaurantBrandRepository)(nil).GetAllCategories), ctx)
}

// GetByID mocks base method.
func (m *MockRestaurantBrandRepository) GetByID(ctx context.Context, id int64) (domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRestaurantBrandRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRestaurantBrandRepository)(nil).GetByID), ctx, id)
}

// GetRestaurantBrandsByCategory mocks base method.
func (m *MockRestaurantBrandRepository) GetRestaurantBrandsByCategory(ctx context.Context, categoryID int64, limit, offset int) ([]domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurantBrandsByCategory", ctx, categoryID, limit, offset)
	ret0, _ := ret[0].([]domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestaurantBrandsByCategory indicates an expected call of GetRestaurantBrandsByCategory.
func (mr *MockRestaurantBrandRepositoryMockRecorder) GetRestaurantBrandsByCategory(ctx, categoryID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurantBrandsByCategory", reflect.TypeOf((*MockRestaurantBrandRepository)(nil).GetRestaurantBrandsByCategory), ctx, categoryID, limit, offset)
}

// GetRestaurantBrandsByCategoryName mocks base method.
func (m *MockRestaurantBrandRepository) GetRestaurantBrandsByCategoryName(ctx context.Context, categoryName string, limit, offset int) ([]domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurantBrandsByCategoryName", ctx, categoryName, limit, offset)
	ret0, _ := ret[0].([]domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestaurantBrandsByCategoryName indicates an expected call of GetRestaurantBrandsByCategoryName.
func (mr *MockRestaurantBrandRepositoryMockRecorder) GetRestaurantBrandsByCategoryName(ctx, categoryName, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurantBrandsByCategoryName", reflect.TypeOf((*MockRestaurantBrandRepository)(nil).GetRestaurantBrandsByCategoryName), ctx, categoryName, limit, offset)
}

// GetRestaurantBrandsByIDs mocks base method.
func (m *MockRestaurantBrandRepository) GetRestaurantBrandsByIDs(ctx context.Context, ids []int64) ([]domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurantBrandsByIDs", ctx, ids)
	ret0, _ := ret[0].([]domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestaurantBrandsByIDs indicates an expected call of GetRestaurantBrandsByIDs.
func (mr *MockRestaurantBrandRepositoryMockRecorder) GetRestaurantBrandsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurantBrandsByIDs", reflect.TypeOf((*MockRestaurantBrandRepository)(nil).GetRestaurantBrandsByIDs), ctx, ids)
}

// GetRestaurantBrandsList mocks base method.
func (m *MockRestaurantBrandRepository) GetRestaurantBrandsList(ctx context.Context, limit, offset int) ([]domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurantBrandsList", ctx, limit, offset)
	ret0, _ := ret[0].([]domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestaurantBrandsList indicates an expected call of GetRestaurantBrandsList.
func (mr *MockRestaurantBrandRepositoryMockRecorder) GetRestaurantBrandsList(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurantBrandsList", reflect.TypeOf((*MockRestaurantBrandRepository)(nil).GetRestaurantBrandsList), ctx, limit, offset)
}

// RecommendByCategorySimilarity mocks base method.
func (m *MockRestaurantBrandRepository) RecommendByCategorySimilarity(ctx context.Context, seedBrandIDs, excludeBrandIDs []int64, limit int) ([]domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecommendByCategorySimilarity", ctx, seedBrandIDs, excludeBrandIDs, limit)
	ret0, _ := ret[0].([]domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecommendByCategorySimilarity indicates an expected call of RecommendByCategorySimilarity.
func (mr *MockRestaurantBrandRepositoryMockRecorder) RecommendByCategorySimilarity(ctx, seedBrandIDs, excludeBrandIDs, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecommendByCategorySimilarity", reflect.TypeOf((*MockRestaurantBrandRepository)(nil).RecommendByCategorySimilarity), ctx, seedBrandIDs, excludeBrandIDs, limit)
}

// SearchRestaurantBrands mocks base method.
func (m *MockRestaurantBrandRepository) SearchRestaurantBrands(ctx context.Context, query string, limit, offset int) ([]domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRestaurantBrands", ctx, query, limit, offset)
	ret0, _ := ret[0].([]domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRestaurantBrands indicates an expected call of SearchRestaurantBrands.
func (mr *MockRestaurantBrandRepositoryMockRecorder) SearchRestaurantBrands(ctx, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRestaurantBrands", reflect.TypeOf((*MockRestaurantBrandRepository)(nil).SearchRestaurantBrands), ctx, query, limit, offset)
}

// Update mocks base method.
func (m *MockRestaurantBrandRepository) Update(ctx context.Context, b domain.RestaurantBrand) (domain.RestaurantBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, b)
	ret0, _ := ret[0].(domain.RestaurantBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRestaurantBrandRepositoryMockRecorder) Update(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRestaurantBrandRepository)(nil).Update), ctx, b)
}
