// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package postgres

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonCd30393bDecodeGithubComGoParkMailRu20261NaNcatsServicesAddressInternalRepositoryPostgres(in *jlexer.Lexer, out *idempotencyResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "public_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PublicID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCd30393bEncodeGithubComGoParkMailRu20261NaNcatsServicesAddressInternalRepositoryPostgres(out *jwriter.Writer, in idempotencyResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.PublicID != "" {
		const prefix string = ",\"public_id\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.PublicID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v idempotencyResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCd30393bEncodeGithubComGoParkMailRu20261NaNcatsServicesAddressInternalRepositoryPostgres(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v idempotencyResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCd30393bEncodeGithubComGoParkMailRu20261NaNcatsServicesAddressInternalRepositoryPostgres(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *idempotencyResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCd30393bDecodeGithubComGoParkMailRu20261NaNcatsServicesAddressInternalRepositoryPostgres(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *idempotencyResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCd30393bDecodeGithubComGoParkMailRu20261NaNcatsServicesAddressInternalRepositoryPostgres(l, v)
}
