name: CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  
permissions:
  contents: read
  packages: write

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: api-gateway
            context_path: ./api-gateway
          - service: address
            context_path: ./services/address
          - service: analytics
            context_path: ./services/analytics
          - service: auth
            context_path: ./services/auth
          - service: cart
            context_path: ./services/cart
          - service: order
            context_path: ./services/order
          - service: payment
            context_path: ./services/payment
          - service: restaurant
            context_path: ./services/restaurant
          - service: support
            context_path: ./services/support
          - service: user
            context_path: ./services/user

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check for changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            changed:
              - '${{ matrix.context_path }}/**'
              - 'shared/**'
              - 'go.mod'
              - 'go.sum'

      - name: Setup Go
        if: steps.filter.outputs.changed == 'true'
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.1'
          cache: true

      - name: Run golangci-lint
        if: steps.filter.outputs.changed == 'true'
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
          args: --timeout=5m ${{ matrix.context_path }}/... ./shared/...

      - name: Run Unit Tests
        if: steps.filter.outputs.changed == 'true'
        run: go test -v ${{ matrix.context_path }}/...
            
  build-and-push:
    needs: lint-and-test
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: api-gateway
            context_path: ./api-gateway
            build_path: ./api-gateway/cmd/api/main.go
          - service: address
            context_path: ./services/address
            build_path: ./services/address/cmd/main.go
          - service: analytics
            context_path: ./services/analytics
            build_path: ./services/analytics/cmd/main.go
          - service: auth
            context_path: ./services/auth
            build_path: ./services/auth/cmd/main.go
          - service: cart
            context_path: ./services/cart
            build_path: ./services/cart/cmd/main.go
          - service: order
            context_path: ./services/order
            build_path: ./services/order/cmd/main.go
          - service: payment
            context_path: ./services/payment
            build_path: ./services/payment/cmd/main.go
          - service: restaurant
            context_path: ./services/restaurant
            build_path: ./services/restaurant/cmd/main.go
          - service: support
            context_path: ./services/support
            build_path: ./services/support/cmd/main.go
          - service: user
            context_path: ./services/user
            build_path: ./services/user/cmd/main.go

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check for changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            changed:
              - '${{ matrix.context_path }}/**'
              - 'shared/**'
              - 'go.mod'
              - 'go.sum'
              - 'Dockerfile'

      - name: Login to Github Container Registry
        if: steps.filter.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Repository Owner
        if: steps.filter.outputs.changed == 'true'
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build and push
        if: steps.filter.outputs.changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_OWNER }}/2026_1_nancats/${{ matrix.service }}:latest
          build-args: |
            BUILD_PATH=${{ matrix.build_path }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - service: api-gateway
            context_path: ./api-gateway
          - service: address
            context_path: ./services/address
          - service: analytics
            context_path: ./services/analytics
          - service: auth
            context_path: ./services/auth
          - service: cart
            context_path: ./services/cart
          - service: order
            context_path: ./services/order
          - service: payment
            context_path: ./services/payment
          - service: restaurant
            context_path: ./services/restaurant
          - service: support
            context_path: ./services/support
          - service: user
            context_path: ./services/user

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check for changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            changed:
              - '${{ matrix.context_path }}/**'
              - 'shared/**'
              - 'helm/**'
      
      - name: Copy Helm charts to server
        if: steps.filter.outputs.changed == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "helm/**"
          target: "/home/ubuntu/k8s_manifests/"

      - name: SSH to k3s server and Deploy via Helm
        if: steps.filter.outputs.changed == 'true'
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
            echo "Деплой сервиса ${{ matrix.service }}"
            helm upgrade --install ${{ matrix.service }}-release /home/ubuntu/k8s_manifests/helm/nancats-service \
              -f /home/ubuntu/k8s_manifests/helm/values-${{ matrix.service }}.yaml \
              --set image.repository=ghcr.io/${REPO_OWNER}/2026_1_nancats/${{ matrix.service }} \
              --set image.tag=latest \
              --set serviceName=${{ matrix.service }}-service \
              --set deployedAt="${{ github.sha }}-$(date -u +%s)"
